// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessService creates a new instance of MockProcessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessService {
	mock := &MockProcessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessService is an autogenerated mock type for the ProcessService type
type MockProcessService struct {
	mock.Mock
}

type MockProcessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessService) EXPECT() *MockProcessService_Expecter {
	return &MockProcessService_Expecter{mock: &_m.Mock}
}

// GetProcessCount provides a mock function for the type MockProcessService
func (_mock *MockProcessService) GetProcessCount() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProcessCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessService_GetProcessCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProcessCount'
type MockProcessService_GetProcessCount_Call struct {
	*mock.Call
}

// GetProcessCount is a helper method to define mock.On call
func (_e *MockProcessService_Expecter) GetProcessCount() *MockProcessService_GetProcessCount_Call {
	return &MockProcessService_GetProcessCount_Call{Call: _e.mock.On("GetProcessCount")}
}

func (_c *MockProcessService_GetProcessCount_Call) Run(run func()) *MockProcessService_GetProcessCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessService_GetProcessCount_Call) Return(n int, err error) *MockProcessService_GetProcessCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockProcessService_GetProcessCount_Call) RunAndReturn(run func() (int, error)) *MockProcessService_GetProcessCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetProcessList provides a mock function for the type MockProcessService
func (_mock *MockProcessService) GetProcessList() ([]ProcessInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProcessList")
	}

	var r0 []ProcessInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]ProcessInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []ProcessInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ProcessInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessService_GetProcessList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProcessList'
type MockProcessService_GetProcessList_Call struct {
	*mock.Call
}

// GetProcessList is a helper method to define mock.On call
func (_e *MockProcessService_Expecter) GetProcessList() *MockProcessService_GetProcessList_Call {
	return &MockProcessService_GetProcessList_Call{Call: _e.mock.On("GetProcessList")}
}

func (_c *MockProcessService_GetProcessList_Call) Run(run func()) *MockProcessService_GetProcessList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessService_GetProcessList_Call) Return(processInfos []ProcessInfo, err error) *MockProcessService_GetProcessList_Call {
	_c.Call.Return(processInfos, err)
	return _c
}

func (_c *MockProcessService_GetProcessList_Call) RunAndReturn(run func() ([]ProcessInfo, error)) *MockProcessService_GetProcessList_Call {
	_c.Call.Return(run)
	return _c
}

// IsProcessRunning provides a mock function for the type MockProcessService
func (_mock *MockProcessService) IsProcessRunning(pathOfBinary string) (bool, error) {
	ret := _mock.Called(pathOfBinary)

	if len(ret) == 0 {
		panic("no return value specified for IsProcessRunning")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(pathOfBinary)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(pathOfBinary)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pathOfBinary)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessService_IsProcessRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsProcessRunning'
type MockProcessService_IsProcessRunning_Call struct {
	*mock.Call
}

// IsProcessRunning is a helper method to define mock.On call
//   - pathOfBinary string
func (_e *MockProcessService_Expecter) IsProcessRunning(pathOfBinary interface{}) *MockProcessService_IsProcessRunning_Call {
	return &MockProcessService_IsProcessRunning_Call{Call: _e.mock.On("IsProcessRunning", pathOfBinary)}
}

func (_c *MockProcessService_IsProcessRunning_Call) Run(run func(pathOfBinary string)) *MockProcessService_IsProcessRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcessService_IsProcessRunning_Call) Return(b bool, err error) *MockProcessService_IsProcessRunning_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockProcessService_IsProcessRunning_Call) RunAndReturn(run func(pathOfBinary string) (bool, error)) *MockProcessService_IsProcessRunning_Call {
	_c.Call.Return(run)
	return _c
}

// StartProcess provides a mock function for the type MockProcessService
func (_mock *MockProcessService) StartProcess(pathOfBinary string, startParams ...string) error {
	var tmpRet mock.Arguments
	if len(startParams) > 0 {
		tmpRet = _mock.Called(pathOfBinary, startParams)
	} else {
		tmpRet = _mock.Called(pathOfBinary)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for StartProcess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = returnFunc(pathOfBinary, startParams...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcessService_StartProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartProcess'
type MockProcessService_StartProcess_Call struct {
	*mock.Call
}

// StartProcess is a helper method to define mock.On call
//   - pathOfBinary string
//   - startParams ...string
func (_e *MockProcessService_Expecter) StartProcess(pathOfBinary interface{}, startParams ...interface{}) *MockProcessService_StartProcess_Call {
	return &MockProcessService_StartProcess_Call{Call: _e.mock.On("StartProcess",
		append([]interface{}{pathOfBinary}, startParams...)...)}
}

func (_c *MockProcessService_StartProcess_Call) Run(run func(pathOfBinary string, startParams ...string)) *MockProcessService_StartProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockProcessService_StartProcess_Call) Return(err error) *MockProcessService_StartProcess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcessService_StartProcess_Call) RunAndReturn(run func(pathOfBinary string, startParams ...string) error) *MockProcessService_StartProcess_Call {
	_c.Call.Return(run)
	return _c
}

// StopProcess provides a mock function for the type MockProcessService
func (_mock *MockProcessService) StopProcess(pathOfBinary string) error {
	ret := _mock.Called(pathOfBinary)

	if len(ret) == 0 {
		panic("no return value specified for StopProcess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(pathOfBinary)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcessService_StopProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopProcess'
type MockProcessService_StopProcess_Call struct {
	*mock.Call
}

// StopProcess is a helper method to define mock.On call
//   - pathOfBinary string
func (_e *MockProcessService_Expecter) StopProcess(pathOfBinary interface{}) *MockProcessService_StopProcess_Call {
	return &MockProcessService_StopProcess_Call{Call: _e.mock.On("StopProcess", pathOfBinary)}
}

func (_c *MockProcessService_StopProcess_Call) Run(run func(pathOfBinary string)) *MockProcessService_StopProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcessService_StopProcess_Call) Return(err error) *MockProcessService_StopProcess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcessService_StopProcess_Call) RunAndReturn(run func(pathOfBinary string) error) *MockProcessService_StopProcess_Call {
	_c.Call.Return(run)
	return _c
}
