// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"io/fs"
	"os"

	"github.com/project-agonyl/agonyl-utils-go/dropfile"
	"github.com/project-agonyl/agonyl-utils-go/itemcombinationdata"
	"github.com/project-agonyl/agonyl-utils-go/itemfile"
	"github.com/project-agonyl/agonyl-utils-go/questfile"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileEditorService creates a new instance of MockFileEditorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileEditorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileEditorService {
	mock := &MockFileEditorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileEditorService is an autogenerated mock type for the FileEditorService type
type MockFileEditorService struct {
	mock.Mock
}

type MockFileEditorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileEditorService) EXPECT() *MockFileEditorService_Expecter {
	return &MockFileEditorService_Expecter{mock: &_m.Mock}
}

// GetFileAPIEndpoint provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) GetFileAPIEndpoint(path string, fileInfo fs.FileInfo) string {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetFileAPIEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) string); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFileEditorService_GetFileAPIEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileAPIEndpoint'
type MockFileEditorService_GetFileAPIEndpoint_Call struct {
	*mock.Call
}

// GetFileAPIEndpoint is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) GetFileAPIEndpoint(path interface{}, fileInfo interface{}) *MockFileEditorService_GetFileAPIEndpoint_Call {
	return &MockFileEditorService_GetFileAPIEndpoint_Call{Call: _e.mock.On("GetFileAPIEndpoint", path, fileInfo)}
}

func (_c *MockFileEditorService_GetFileAPIEndpoint_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_GetFileAPIEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_GetFileAPIEndpoint_Call) Return(s string) *MockFileEditorService_GetFileAPIEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFileEditorService_GetFileAPIEndpoint_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) string) *MockFileEditorService_GetFileAPIEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileType provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) GetFileType(path string, fileInfo fs.FileInfo) FileType {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetFileType")
	}

	var r0 FileType
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) FileType); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(FileType)
	}
	return r0
}

// MockFileEditorService_GetFileType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileType'
type MockFileEditorService_GetFileType_Call struct {
	*mock.Call
}

// GetFileType is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) GetFileType(path interface{}, fileInfo interface{}) *MockFileEditorService_GetFileType_Call {
	return &MockFileEditorService_GetFileType_Call{Call: _e.mock.On("GetFileType", path, fileInfo)}
}

func (_c *MockFileEditorService_GetFileType_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_GetFileType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_GetFileType_Call) Return(fileType FileType) *MockFileEditorService_GetFileType_Call {
	_c.Call.Return(fileType)
	return _c
}

func (_c *MockFileEditorService_GetFileType_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) FileType) *MockFileEditorService_GetFileType_Call {
	_c.Call.Return(run)
	return _c
}

// Hostname provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) Hostname() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hostname")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_Hostname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hostname'
type MockFileEditorService_Hostname_Call struct {
	*mock.Call
}

// Hostname is a helper method to define mock.On call
func (_e *MockFileEditorService_Expecter) Hostname() *MockFileEditorService_Hostname_Call {
	return &MockFileEditorService_Hostname_Call{Call: _e.mock.On("Hostname")}
}

func (_c *MockFileEditorService_Hostname_Call) Run(run func()) *MockFileEditorService_Hostname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileEditorService_Hostname_Call) Return(s string, err error) *MockFileEditorService_Hostname_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileEditorService_Hostname_Call) RunAndReturn(run func() (string, error)) *MockFileEditorService_Hostname_Call {
	_c.Call.Return(run)
	return _c
}

// IsExist provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsExist(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsExist")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExist'
type MockFileEditorService_IsExist_Call struct {
	*mock.Call
}

// IsExist is a helper method to define mock.On call
//   - err error
func (_e *MockFileEditorService_Expecter) IsExist(err interface{}) *MockFileEditorService_IsExist_Call {
	return &MockFileEditorService_IsExist_Call{Call: _e.mock.On("IsExist", err)}
}

func (_c *MockFileEditorService_IsExist_Call) Run(run func(err error)) *MockFileEditorService_IsExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsExist_Call) Return(b bool) *MockFileEditorService_IsExist_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsExist_Call) RunAndReturn(run func(err error) bool) *MockFileEditorService_IsExist_Call {
	_c.Call.Return(run)
	return _c
}

// IsFileEditable provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsFileEditable(path string, fileInfo fs.FileInfo) bool {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for IsFileEditable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) bool); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsFileEditable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFileEditable'
type MockFileEditorService_IsFileEditable_Call struct {
	*mock.Call
}

// IsFileEditable is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) IsFileEditable(path interface{}, fileInfo interface{}) *MockFileEditorService_IsFileEditable_Call {
	return &MockFileEditorService_IsFileEditable_Call{Call: _e.mock.On("IsFileEditable", path, fileInfo)}
}

func (_c *MockFileEditorService_IsFileEditable_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_IsFileEditable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsFileEditable_Call) Return(b bool) *MockFileEditorService_IsFileEditable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsFileEditable_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) bool) *MockFileEditorService_IsFileEditable_Call {
	_c.Call.Return(run)
	return _c
}

// IsFileViewable provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsFileViewable(path string, fileInfo fs.FileInfo) bool {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for IsFileViewable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) bool); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsFileViewable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFileViewable'
type MockFileEditorService_IsFileViewable_Call struct {
	*mock.Call
}

// IsFileViewable is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) IsFileViewable(path interface{}, fileInfo interface{}) *MockFileEditorService_IsFileViewable_Call {
	return &MockFileEditorService_IsFileViewable_Call{Call: _e.mock.On("IsFileViewable", path, fileInfo)}
}

func (_c *MockFileEditorService_IsFileViewable_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_IsFileViewable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsFileViewable_Call) Return(b bool) *MockFileEditorService_IsFileViewable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsFileViewable_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) bool) *MockFileEditorService_IsFileViewable_Call {
	_c.Call.Return(run)
	return _c
}

// IsNotExist provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsNotExist(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsNotExist")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsNotExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNotExist'
type MockFileEditorService_IsNotExist_Call struct {
	*mock.Call
}

// IsNotExist is a helper method to define mock.On call
//   - err error
func (_e *MockFileEditorService_Expecter) IsNotExist(err interface{}) *MockFileEditorService_IsNotExist_Call {
	return &MockFileEditorService_IsNotExist_Call{Call: _e.mock.On("IsNotExist", err)}
}

func (_c *MockFileEditorService_IsNotExist_Call) Run(run func(err error)) *MockFileEditorService_IsNotExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsNotExist_Call) Return(b bool) *MockFileEditorService_IsNotExist_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsNotExist_Call) RunAndReturn(run func(err error) bool) *MockFileEditorService_IsNotExist_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) MkdirAll(path string, perm fs.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileEditorService_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm fs.FileMode
func (_e *MockFileEditorService_Expecter) MkdirAll(path interface{}, perm interface{}) *MockFileEditorService_MkdirAll_Call {
	return &MockFileEditorService_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFileEditorService_MkdirAll_Call) Run(run func(path string, perm fs.FileMode)) *MockFileEditorService_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileMode
		if args[1] != nil {
			arg1 = args[1].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_MkdirAll_Call) Return(err error) *MockFileEditorService_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_MkdirAll_Call) RunAndReturn(run func(path string, perm fs.FileMode) error) *MockFileEditorService_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) OpenFile(name string, flag int, perm fs.FileMode) (*os.File, error) {
	ret := _mock.Called(name, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, fs.FileMode) (*os.File, error)); ok {
		return returnFunc(name, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, fs.FileMode) *os.File); ok {
		r0 = returnFunc(name, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, fs.FileMode) error); ok {
		r1 = returnFunc(name, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type MockFileEditorService_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - name string
//   - flag int
//   - perm fs.FileMode
func (_e *MockFileEditorService_Expecter) OpenFile(name interface{}, flag interface{}, perm interface{}) *MockFileEditorService_OpenFile_Call {
	return &MockFileEditorService_OpenFile_Call{Call: _e.mock.On("OpenFile", name, flag, perm)}
}

func (_c *MockFileEditorService_OpenFile_Call) Run(run func(name string, flag int, perm fs.FileMode)) *MockFileEditorService_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileEditorService_OpenFile_Call) Return(file *os.File, err error) *MockFileEditorService_OpenFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileEditorService_OpenFile_Call) RunAndReturn(run func(name string, flag int, perm fs.FileMode) (*os.File, error)) *MockFileEditorService_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClientIT0FileBytes provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadClientIT0FileBytes(data []byte) ([]itemfile.Item, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ReadClientIT0FileBytes")
	}

	var r0 []itemfile.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]itemfile.Item, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []itemfile.Item); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]itemfile.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadClientIT0FileBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClientIT0FileBytes'
type MockFileEditorService_ReadClientIT0FileBytes_Call struct {
	*mock.Call
}

// ReadClientIT0FileBytes is a helper method to define mock.On call
//   - data []byte
func (_e *MockFileEditorService_Expecter) ReadClientIT0FileBytes(data interface{}) *MockFileEditorService_ReadClientIT0FileBytes_Call {
	return &MockFileEditorService_ReadClientIT0FileBytes_Call{Call: _e.mock.On("ReadClientIT0FileBytes", data)}
}

func (_c *MockFileEditorService_ReadClientIT0FileBytes_Call) Run(run func(data []byte)) *MockFileEditorService_ReadClientIT0FileBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadClientIT0FileBytes_Call) Return(items []itemfile.Item, err error) *MockFileEditorService_ReadClientIT0FileBytes_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockFileEditorService_ReadClientIT0FileBytes_Call) RunAndReturn(run func(data []byte) ([]itemfile.Item, error)) *MockFileEditorService_ReadClientIT0FileBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClientIT1FileBytes provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadClientIT1FileBytes(data []byte) ([]itemfile.Item, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ReadClientIT1FileBytes")
	}

	var r0 []itemfile.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]itemfile.Item, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []itemfile.Item); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]itemfile.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadClientIT1FileBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClientIT1FileBytes'
type MockFileEditorService_ReadClientIT1FileBytes_Call struct {
	*mock.Call
}

// ReadClientIT1FileBytes is a helper method to define mock.On call
//   - data []byte
func (_e *MockFileEditorService_Expecter) ReadClientIT1FileBytes(data interface{}) *MockFileEditorService_ReadClientIT1FileBytes_Call {
	return &MockFileEditorService_ReadClientIT1FileBytes_Call{Call: _e.mock.On("ReadClientIT1FileBytes", data)}
}

func (_c *MockFileEditorService_ReadClientIT1FileBytes_Call) Run(run func(data []byte)) *MockFileEditorService_ReadClientIT1FileBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadClientIT1FileBytes_Call) Return(items []itemfile.Item, err error) *MockFileEditorService_ReadClientIT1FileBytes_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockFileEditorService_ReadClientIT1FileBytes_Call) RunAndReturn(run func(data []byte) ([]itemfile.Item, error)) *MockFileEditorService_ReadClientIT1FileBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClientIT2FileBytes provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadClientIT2FileBytes(data []byte) ([]itemfile.Item, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ReadClientIT2FileBytes")
	}

	var r0 []itemfile.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]itemfile.Item, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []itemfile.Item); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]itemfile.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadClientIT2FileBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClientIT2FileBytes'
type MockFileEditorService_ReadClientIT2FileBytes_Call struct {
	*mock.Call
}

// ReadClientIT2FileBytes is a helper method to define mock.On call
//   - data []byte
func (_e *MockFileEditorService_Expecter) ReadClientIT2FileBytes(data interface{}) *MockFileEditorService_ReadClientIT2FileBytes_Call {
	return &MockFileEditorService_ReadClientIT2FileBytes_Call{Call: _e.mock.On("ReadClientIT2FileBytes", data)}
}

func (_c *MockFileEditorService_ReadClientIT2FileBytes_Call) Run(run func(data []byte)) *MockFileEditorService_ReadClientIT2FileBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadClientIT2FileBytes_Call) Return(items []itemfile.Item, err error) *MockFileEditorService_ReadClientIT2FileBytes_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockFileEditorService_ReadClientIT2FileBytes_Call) RunAndReturn(run func(data []byte) ([]itemfile.Item, error)) *MockFileEditorService_ReadClientIT2FileBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClientIT3FileBytes provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadClientIT3FileBytes(data []byte) ([]itemfile.Item, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ReadClientIT3FileBytes")
	}

	var r0 []itemfile.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]itemfile.Item, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []itemfile.Item); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]itemfile.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadClientIT3FileBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClientIT3FileBytes'
type MockFileEditorService_ReadClientIT3FileBytes_Call struct {
	*mock.Call
}

// ReadClientIT3FileBytes is a helper method to define mock.On call
//   - data []byte
func (_e *MockFileEditorService_Expecter) ReadClientIT3FileBytes(data interface{}) *MockFileEditorService_ReadClientIT3FileBytes_Call {
	return &MockFileEditorService_ReadClientIT3FileBytes_Call{Call: _e.mock.On("ReadClientIT3FileBytes", data)}
}

func (_c *MockFileEditorService_ReadClientIT3FileBytes_Call) Run(run func(data []byte)) *MockFileEditorService_ReadClientIT3FileBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadClientIT3FileBytes_Call) Return(items []itemfile.Item, err error) *MockFileEditorService_ReadClientIT3FileBytes_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockFileEditorService_ReadClientIT3FileBytes_Call) RunAndReturn(run func(data []byte) ([]itemfile.Item, error)) *MockFileEditorService_ReadClientIT3FileBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClientMapFileBytes provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadClientMapFileBytes(data []byte) ([]MapClientData, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ReadClientMapFileBytes")
	}

	var r0 []MapClientData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]MapClientData, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []MapClientData); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MapClientData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadClientMapFileBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClientMapFileBytes'
type MockFileEditorService_ReadClientMapFileBytes_Call struct {
	*mock.Call
}

// ReadClientMapFileBytes is a helper method to define mock.On call
//   - data []byte
func (_e *MockFileEditorService_Expecter) ReadClientMapFileBytes(data interface{}) *MockFileEditorService_ReadClientMapFileBytes_Call {
	return &MockFileEditorService_ReadClientMapFileBytes_Call{Call: _e.mock.On("ReadClientMapFileBytes", data)}
}

func (_c *MockFileEditorService_ReadClientMapFileBytes_Call) Run(run func(data []byte)) *MockFileEditorService_ReadClientMapFileBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadClientMapFileBytes_Call) Return(mapClientDatas []MapClientData, err error) *MockFileEditorService_ReadClientMapFileBytes_Call {
	_c.Call.Return(mapClientDatas, err)
	return _c
}

func (_c *MockFileEditorService_ReadClientMapFileBytes_Call) RunAndReturn(run func(data []byte) ([]MapClientData, error)) *MockFileEditorService_ReadClientMapFileBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClientMapFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadClientMapFileData(path string) ([]MapClientData, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadClientMapFileData")
	}

	var r0 []MapClientData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]MapClientData, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []MapClientData); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MapClientData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadClientMapFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClientMapFileData'
type MockFileEditorService_ReadClientMapFileData_Call struct {
	*mock.Call
}

// ReadClientMapFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadClientMapFileData(path interface{}) *MockFileEditorService_ReadClientMapFileData_Call {
	return &MockFileEditorService_ReadClientMapFileData_Call{Call: _e.mock.On("ReadClientMapFileData", path)}
}

func (_c *MockFileEditorService_ReadClientMapFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadClientMapFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadClientMapFileData_Call) Return(mapClientDatas []MapClientData, err error) *MockFileEditorService_ReadClientMapFileData_Call {
	_c.Call.Return(mapClientDatas, err)
	return _c
}

func (_c *MockFileEditorService_ReadClientMapFileData_Call) RunAndReturn(run func(path string) ([]MapClientData, error)) *MockFileEditorService_ReadClientMapFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClientMonsterFileBytes provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadClientMonsterFileBytes(data []byte) ([]MonsterClientData, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ReadClientMonsterFileBytes")
	}

	var r0 []MonsterClientData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]MonsterClientData, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []MonsterClientData); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MonsterClientData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadClientMonsterFileBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClientMonsterFileBytes'
type MockFileEditorService_ReadClientMonsterFileBytes_Call struct {
	*mock.Call
}

// ReadClientMonsterFileBytes is a helper method to define mock.On call
//   - data []byte
func (_e *MockFileEditorService_Expecter) ReadClientMonsterFileBytes(data interface{}) *MockFileEditorService_ReadClientMonsterFileBytes_Call {
	return &MockFileEditorService_ReadClientMonsterFileBytes_Call{Call: _e.mock.On("ReadClientMonsterFileBytes", data)}
}

func (_c *MockFileEditorService_ReadClientMonsterFileBytes_Call) Run(run func(data []byte)) *MockFileEditorService_ReadClientMonsterFileBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadClientMonsterFileBytes_Call) Return(monsterClientDatas []MonsterClientData, err error) *MockFileEditorService_ReadClientMonsterFileBytes_Call {
	_c.Call.Return(monsterClientDatas, err)
	return _c
}

func (_c *MockFileEditorService_ReadClientMonsterFileBytes_Call) RunAndReturn(run func(data []byte) ([]MonsterClientData, error)) *MockFileEditorService_ReadClientMonsterFileBytes_Call {
	_c.Call.Return(run)
	return _c
}

// ReadClientMonsterFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadClientMonsterFileData(path string) ([]MonsterClientData, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadClientMonsterFileData")
	}

	var r0 []MonsterClientData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]MonsterClientData, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []MonsterClientData); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MonsterClientData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadClientMonsterFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadClientMonsterFileData'
type MockFileEditorService_ReadClientMonsterFileData_Call struct {
	*mock.Call
}

// ReadClientMonsterFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadClientMonsterFileData(path interface{}) *MockFileEditorService_ReadClientMonsterFileData_Call {
	return &MockFileEditorService_ReadClientMonsterFileData_Call{Call: _e.mock.On("ReadClientMonsterFileData", path)}
}

func (_c *MockFileEditorService_ReadClientMonsterFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadClientMonsterFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadClientMonsterFileData_Call) Return(monsterClientDatas []MonsterClientData, err error) *MockFileEditorService_ReadClientMonsterFileData_Call {
	_c.Call.Return(monsterClientDatas, err)
	return _c
}

func (_c *MockFileEditorService_ReadClientMonsterFileData_Call) RunAndReturn(run func(path string) ([]MonsterClientData, error)) *MockFileEditorService_ReadClientMonsterFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadDir(name string) ([]fs.DirEntry, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockFileEditorService_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *MockFileEditorService_Expecter) ReadDir(name interface{}) *MockFileEditorService_ReadDir_Call {
	return &MockFileEditorService_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *MockFileEditorService_ReadDir_Call) Run(run func(name string)) *MockFileEditorService_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadDir_Call) Return(dirEntrys []fs.DirEntry, err error) *MockFileEditorService_ReadDir_Call {
	_c.Call.Return(dirEntrys, err)
	return _c
}

func (_c *MockFileEditorService_ReadDir_Call) RunAndReturn(run func(name string) ([]fs.DirEntry, error)) *MockFileEditorService_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDropFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadDropFileData(path string) (dropfile.DropFile, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadDropFileData")
	}

	var r0 dropfile.DropFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (dropfile.DropFile, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) dropfile.DropFile); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dropfile.DropFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadDropFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDropFileData'
type MockFileEditorService_ReadDropFileData_Call struct {
	*mock.Call
}

// ReadDropFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadDropFileData(path interface{}) *MockFileEditorService_ReadDropFileData_Call {
	return &MockFileEditorService_ReadDropFileData_Call{Call: _e.mock.On("ReadDropFileData", path)}
}

func (_c *MockFileEditorService_ReadDropFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadDropFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadDropFileData_Call) Return(dropFile dropfile.DropFile, err error) *MockFileEditorService_ReadDropFileData_Call {
	_c.Call.Return(dropFile, err)
	return _c
}

func (_c *MockFileEditorService_ReadDropFileData_Call) RunAndReturn(run func(path string) (dropfile.DropFile, error)) *MockFileEditorService_ReadDropFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadFile(name string) ([]byte, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFileEditorService_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name string
func (_e *MockFileEditorService_Expecter) ReadFile(name interface{}) *MockFileEditorService_ReadFile_Call {
	return &MockFileEditorService_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *MockFileEditorService_ReadFile_Call) Run(run func(name string)) *MockFileEditorService_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadFile_Call) Return(bytes []byte, err error) *MockFileEditorService_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFileEditorService_ReadFile_Call) RunAndReturn(run func(name string) ([]byte, error)) *MockFileEditorService_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReadIT0ExItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadIT0ExItemFileData(path string) (itemfile.IT0ExFile, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadIT0ExItemFileData")
	}

	var r0 itemfile.IT0ExFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (itemfile.IT0ExFile, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) itemfile.IT0ExFile); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(itemfile.IT0ExFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadIT0ExItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadIT0ExItemFileData'
type MockFileEditorService_ReadIT0ExItemFileData_Call struct {
	*mock.Call
}

// ReadIT0ExItemFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadIT0ExItemFileData(path interface{}) *MockFileEditorService_ReadIT0ExItemFileData_Call {
	return &MockFileEditorService_ReadIT0ExItemFileData_Call{Call: _e.mock.On("ReadIT0ExItemFileData", path)}
}

func (_c *MockFileEditorService_ReadIT0ExItemFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadIT0ExItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadIT0ExItemFileData_Call) Return(iT0ExFile itemfile.IT0ExFile, err error) *MockFileEditorService_ReadIT0ExItemFileData_Call {
	_c.Call.Return(iT0ExFile, err)
	return _c
}

func (_c *MockFileEditorService_ReadIT0ExItemFileData_Call) RunAndReturn(run func(path string) (itemfile.IT0ExFile, error)) *MockFileEditorService_ReadIT0ExItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadIT0ItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadIT0ItemFileData(path string) (itemfile.IT0File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadIT0ItemFileData")
	}

	var r0 itemfile.IT0File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (itemfile.IT0File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) itemfile.IT0File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(itemfile.IT0File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadIT0ItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadIT0ItemFileData'
type MockFileEditorService_ReadIT0ItemFileData_Call struct {
	*mock.Call
}

// ReadIT0ItemFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadIT0ItemFileData(path interface{}) *MockFileEditorService_ReadIT0ItemFileData_Call {
	return &MockFileEditorService_ReadIT0ItemFileData_Call{Call: _e.mock.On("ReadIT0ItemFileData", path)}
}

func (_c *MockFileEditorService_ReadIT0ItemFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadIT0ItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadIT0ItemFileData_Call) Return(iT0File itemfile.IT0File, err error) *MockFileEditorService_ReadIT0ItemFileData_Call {
	_c.Call.Return(iT0File, err)
	return _c
}

func (_c *MockFileEditorService_ReadIT0ItemFileData_Call) RunAndReturn(run func(path string) (itemfile.IT0File, error)) *MockFileEditorService_ReadIT0ItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadIT1ItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadIT1ItemFileData(path string) (itemfile.IT1File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadIT1ItemFileData")
	}

	var r0 itemfile.IT1File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (itemfile.IT1File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) itemfile.IT1File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(itemfile.IT1File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadIT1ItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadIT1ItemFileData'
type MockFileEditorService_ReadIT1ItemFileData_Call struct {
	*mock.Call
}

// ReadIT1ItemFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadIT1ItemFileData(path interface{}) *MockFileEditorService_ReadIT1ItemFileData_Call {
	return &MockFileEditorService_ReadIT1ItemFileData_Call{Call: _e.mock.On("ReadIT1ItemFileData", path)}
}

func (_c *MockFileEditorService_ReadIT1ItemFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadIT1ItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadIT1ItemFileData_Call) Return(iT1File itemfile.IT1File, err error) *MockFileEditorService_ReadIT1ItemFileData_Call {
	_c.Call.Return(iT1File, err)
	return _c
}

func (_c *MockFileEditorService_ReadIT1ItemFileData_Call) RunAndReturn(run func(path string) (itemfile.IT1File, error)) *MockFileEditorService_ReadIT1ItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadIT2ItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadIT2ItemFileData(path string) (itemfile.IT2File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadIT2ItemFileData")
	}

	var r0 itemfile.IT2File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (itemfile.IT2File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) itemfile.IT2File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(itemfile.IT2File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadIT2ItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadIT2ItemFileData'
type MockFileEditorService_ReadIT2ItemFileData_Call struct {
	*mock.Call
}

// ReadIT2ItemFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadIT2ItemFileData(path interface{}) *MockFileEditorService_ReadIT2ItemFileData_Call {
	return &MockFileEditorService_ReadIT2ItemFileData_Call{Call: _e.mock.On("ReadIT2ItemFileData", path)}
}

func (_c *MockFileEditorService_ReadIT2ItemFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadIT2ItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadIT2ItemFileData_Call) Return(iT2File itemfile.IT2File, err error) *MockFileEditorService_ReadIT2ItemFileData_Call {
	_c.Call.Return(iT2File, err)
	return _c
}

func (_c *MockFileEditorService_ReadIT2ItemFileData_Call) RunAndReturn(run func(path string) (itemfile.IT2File, error)) *MockFileEditorService_ReadIT2ItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadIT3ItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadIT3ItemFileData(path string) (itemfile.IT3File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadIT3ItemFileData")
	}

	var r0 itemfile.IT3File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (itemfile.IT3File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) itemfile.IT3File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(itemfile.IT3File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadIT3ItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadIT3ItemFileData'
type MockFileEditorService_ReadIT3ItemFileData_Call struct {
	*mock.Call
}

// ReadIT3ItemFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadIT3ItemFileData(path interface{}) *MockFileEditorService_ReadIT3ItemFileData_Call {
	return &MockFileEditorService_ReadIT3ItemFileData_Call{Call: _e.mock.On("ReadIT3ItemFileData", path)}
}

func (_c *MockFileEditorService_ReadIT3ItemFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadIT3ItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadIT3ItemFileData_Call) Return(iT3File itemfile.IT3File, err error) *MockFileEditorService_ReadIT3ItemFileData_Call {
	_c.Call.Return(iT3File, err)
	return _c
}

func (_c *MockFileEditorService_ReadIT3ItemFileData_Call) RunAndReturn(run func(path string) (itemfile.IT3File, error)) *MockFileEditorService_ReadIT3ItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadItemCombinationData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadItemCombinationData(path string) (itemcombinationdata.ItemCombinationData, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadItemCombinationData")
	}

	var r0 itemcombinationdata.ItemCombinationData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (itemcombinationdata.ItemCombinationData, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) itemcombinationdata.ItemCombinationData); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(itemcombinationdata.ItemCombinationData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadItemCombinationData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadItemCombinationData'
type MockFileEditorService_ReadItemCombinationData_Call struct {
	*mock.Call
}

// ReadItemCombinationData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadItemCombinationData(path interface{}) *MockFileEditorService_ReadItemCombinationData_Call {
	return &MockFileEditorService_ReadItemCombinationData_Call{Call: _e.mock.On("ReadItemCombinationData", path)}
}

func (_c *MockFileEditorService_ReadItemCombinationData_Call) Run(run func(path string)) *MockFileEditorService_ReadItemCombinationData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadItemCombinationData_Call) Return(itemCombinationData itemcombinationdata.ItemCombinationData, err error) *MockFileEditorService_ReadItemCombinationData_Call {
	_c.Call.Return(itemCombinationData, err)
	return _c
}

func (_c *MockFileEditorService_ReadItemCombinationData_Call) RunAndReturn(run func(path string) (itemcombinationdata.ItemCombinationData, error)) *MockFileEditorService_ReadItemCombinationData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadNPCFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadNPCFileData(path string) (*NPCFileData, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadNPCFileData")
	}

	var r0 *NPCFileData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*NPCFileData, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *NPCFileData); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NPCFileData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadNPCFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadNPCFileData'
type MockFileEditorService_ReadNPCFileData_Call struct {
	*mock.Call
}

// ReadNPCFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadNPCFileData(path interface{}) *MockFileEditorService_ReadNPCFileData_Call {
	return &MockFileEditorService_ReadNPCFileData_Call{Call: _e.mock.On("ReadNPCFileData", path)}
}

func (_c *MockFileEditorService_ReadNPCFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadNPCFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadNPCFileData_Call) Return(nPCFileData *NPCFileData, err error) *MockFileEditorService_ReadNPCFileData_Call {
	_c.Call.Return(nPCFileData, err)
	return _c
}

func (_c *MockFileEditorService_ReadNPCFileData_Call) RunAndReturn(run func(path string) (*NPCFileData, error)) *MockFileEditorService_ReadNPCFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadQuestFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadQuestFileData(path string) (questfile.QuestFile, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadQuestFileData")
	}

	var r0 questfile.QuestFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (questfile.QuestFile, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) questfile.QuestFile); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(questfile.QuestFile)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadQuestFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadQuestFileData'
type MockFileEditorService_ReadQuestFileData_Call struct {
	*mock.Call
}

// ReadQuestFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadQuestFileData(path interface{}) *MockFileEditorService_ReadQuestFileData_Call {
	return &MockFileEditorService_ReadQuestFileData_Call{Call: _e.mock.On("ReadQuestFileData", path)}
}

func (_c *MockFileEditorService_ReadQuestFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadQuestFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadQuestFileData_Call) Return(questFile questfile.QuestFile, err error) *MockFileEditorService_ReadQuestFileData_Call {
	_c.Call.Return(questFile, err)
	return _c
}

func (_c *MockFileEditorService_ReadQuestFileData_Call) RunAndReturn(run func(path string) (questfile.QuestFile, error)) *MockFileEditorService_ReadQuestFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadSpawnFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadSpawnFileData(path string) ([]NPCSpawnData, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadSpawnFileData")
	}

	var r0 []NPCSpawnData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]NPCSpawnData, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []NPCSpawnData); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]NPCSpawnData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadSpawnFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadSpawnFileData'
type MockFileEditorService_ReadSpawnFileData_Call struct {
	*mock.Call
}

// ReadSpawnFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadSpawnFileData(path interface{}) *MockFileEditorService_ReadSpawnFileData_Call {
	return &MockFileEditorService_ReadSpawnFileData_Call{Call: _e.mock.On("ReadSpawnFileData", path)}
}

func (_c *MockFileEditorService_ReadSpawnFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadSpawnFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadSpawnFileData_Call) Return(nPCSpawnDatas []NPCSpawnData, err error) *MockFileEditorService_ReadSpawnFileData_Call {
	_c.Call.Return(nPCSpawnDatas, err)
	return _c
}

func (_c *MockFileEditorService_ReadSpawnFileData_Call) RunAndReturn(run func(path string) ([]NPCSpawnData, error)) *MockFileEditorService_ReadSpawnFileData_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) Remove(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockFileEditorService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name string
func (_e *MockFileEditorService_Expecter) Remove(name interface{}) *MockFileEditorService_Remove_Call {
	return &MockFileEditorService_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *MockFileEditorService_Remove_Call) Run(run func(name string)) *MockFileEditorService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_Remove_Call) Return(err error) *MockFileEditorService_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_Remove_Call) RunAndReturn(run func(name string) error) *MockFileEditorService_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) RemoveAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockFileEditorService_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) RemoveAll(path interface{}) *MockFileEditorService_RemoveAll_Call {
	return &MockFileEditorService_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *MockFileEditorService_RemoveAll_Call) Run(run func(path string)) *MockFileEditorService_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_RemoveAll_Call) Return(err error) *MockFileEditorService_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_RemoveAll_Call) RunAndReturn(run func(path string) error) *MockFileEditorService_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) Stat(name string) (fs.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFileEditorService_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *MockFileEditorService_Expecter) Stat(name interface{}) *MockFileEditorService_Stat_Call {
	return &MockFileEditorService_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockFileEditorService_Stat_Call) Run(run func(name string)) *MockFileEditorService_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_Stat_Call) Return(fileInfo fs.FileInfo, err error) *MockFileEditorService_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockFileEditorService_Stat_Call) RunAndReturn(run func(name string) (fs.FileInfo, error)) *MockFileEditorService_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// WriteDropFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteDropFileData(path string, data dropfile.DropFile) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteDropFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, dropfile.DropFile) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteDropFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteDropFileData'
type MockFileEditorService_WriteDropFileData_Call struct {
	*mock.Call
}

// WriteDropFileData is a helper method to define mock.On call
//   - path string
//   - data dropfile.DropFile
func (_e *MockFileEditorService_Expecter) WriteDropFileData(path interface{}, data interface{}) *MockFileEditorService_WriteDropFileData_Call {
	return &MockFileEditorService_WriteDropFileData_Call{Call: _e.mock.On("WriteDropFileData", path, data)}
}

func (_c *MockFileEditorService_WriteDropFileData_Call) Run(run func(path string, data dropfile.DropFile)) *MockFileEditorService_WriteDropFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 dropfile.DropFile
		if args[1] != nil {
			arg1 = args[1].(dropfile.DropFile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteDropFileData_Call) Return(err error) *MockFileEditorService_WriteDropFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteDropFileData_Call) RunAndReturn(run func(path string, data dropfile.DropFile) error) *MockFileEditorService_WriteDropFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteFile(name string, data []byte, perm fs.FileMode) error {
	ret := _mock.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = returnFunc(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFileEditorService_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name string
//   - data []byte
//   - perm fs.FileMode
func (_e *MockFileEditorService_Expecter) WriteFile(name interface{}, data interface{}, perm interface{}) *MockFileEditorService_WriteFile_Call {
	return &MockFileEditorService_WriteFile_Call{Call: _e.mock.On("WriteFile", name, data, perm)}
}

func (_c *MockFileEditorService_WriteFile_Call) Run(run func(name string, data []byte, perm fs.FileMode)) *MockFileEditorService_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteFile_Call) Return(err error) *MockFileEditorService_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteFile_Call) RunAndReturn(run func(name string, data []byte, perm fs.FileMode) error) *MockFileEditorService_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteIT0ExItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteIT0ExItemFileData(path string, data itemfile.IT0ExFile) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteIT0ExItemFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, itemfile.IT0ExFile) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteIT0ExItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteIT0ExItemFileData'
type MockFileEditorService_WriteIT0ExItemFileData_Call struct {
	*mock.Call
}

// WriteIT0ExItemFileData is a helper method to define mock.On call
//   - path string
//   - data itemfile.IT0ExFile
func (_e *MockFileEditorService_Expecter) WriteIT0ExItemFileData(path interface{}, data interface{}) *MockFileEditorService_WriteIT0ExItemFileData_Call {
	return &MockFileEditorService_WriteIT0ExItemFileData_Call{Call: _e.mock.On("WriteIT0ExItemFileData", path, data)}
}

func (_c *MockFileEditorService_WriteIT0ExItemFileData_Call) Run(run func(path string, data itemfile.IT0ExFile)) *MockFileEditorService_WriteIT0ExItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 itemfile.IT0ExFile
		if args[1] != nil {
			arg1 = args[1].(itemfile.IT0ExFile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteIT0ExItemFileData_Call) Return(err error) *MockFileEditorService_WriteIT0ExItemFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteIT0ExItemFileData_Call) RunAndReturn(run func(path string, data itemfile.IT0ExFile) error) *MockFileEditorService_WriteIT0ExItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteIT0ItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteIT0ItemFileData(path string, data itemfile.IT0File) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteIT0ItemFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, itemfile.IT0File) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteIT0ItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteIT0ItemFileData'
type MockFileEditorService_WriteIT0ItemFileData_Call struct {
	*mock.Call
}

// WriteIT0ItemFileData is a helper method to define mock.On call
//   - path string
//   - data itemfile.IT0File
func (_e *MockFileEditorService_Expecter) WriteIT0ItemFileData(path interface{}, data interface{}) *MockFileEditorService_WriteIT0ItemFileData_Call {
	return &MockFileEditorService_WriteIT0ItemFileData_Call{Call: _e.mock.On("WriteIT0ItemFileData", path, data)}
}

func (_c *MockFileEditorService_WriteIT0ItemFileData_Call) Run(run func(path string, data itemfile.IT0File)) *MockFileEditorService_WriteIT0ItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 itemfile.IT0File
		if args[1] != nil {
			arg1 = args[1].(itemfile.IT0File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteIT0ItemFileData_Call) Return(err error) *MockFileEditorService_WriteIT0ItemFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteIT0ItemFileData_Call) RunAndReturn(run func(path string, data itemfile.IT0File) error) *MockFileEditorService_WriteIT0ItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteIT1ItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteIT1ItemFileData(path string, data itemfile.IT1File) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteIT1ItemFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, itemfile.IT1File) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteIT1ItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteIT1ItemFileData'
type MockFileEditorService_WriteIT1ItemFileData_Call struct {
	*mock.Call
}

// WriteIT1ItemFileData is a helper method to define mock.On call
//   - path string
//   - data itemfile.IT1File
func (_e *MockFileEditorService_Expecter) WriteIT1ItemFileData(path interface{}, data interface{}) *MockFileEditorService_WriteIT1ItemFileData_Call {
	return &MockFileEditorService_WriteIT1ItemFileData_Call{Call: _e.mock.On("WriteIT1ItemFileData", path, data)}
}

func (_c *MockFileEditorService_WriteIT1ItemFileData_Call) Run(run func(path string, data itemfile.IT1File)) *MockFileEditorService_WriteIT1ItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 itemfile.IT1File
		if args[1] != nil {
			arg1 = args[1].(itemfile.IT1File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteIT1ItemFileData_Call) Return(err error) *MockFileEditorService_WriteIT1ItemFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteIT1ItemFileData_Call) RunAndReturn(run func(path string, data itemfile.IT1File) error) *MockFileEditorService_WriteIT1ItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteIT2ItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteIT2ItemFileData(path string, data itemfile.IT2File) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteIT2ItemFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, itemfile.IT2File) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteIT2ItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteIT2ItemFileData'
type MockFileEditorService_WriteIT2ItemFileData_Call struct {
	*mock.Call
}

// WriteIT2ItemFileData is a helper method to define mock.On call
//   - path string
//   - data itemfile.IT2File
func (_e *MockFileEditorService_Expecter) WriteIT2ItemFileData(path interface{}, data interface{}) *MockFileEditorService_WriteIT2ItemFileData_Call {
	return &MockFileEditorService_WriteIT2ItemFileData_Call{Call: _e.mock.On("WriteIT2ItemFileData", path, data)}
}

func (_c *MockFileEditorService_WriteIT2ItemFileData_Call) Run(run func(path string, data itemfile.IT2File)) *MockFileEditorService_WriteIT2ItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 itemfile.IT2File
		if args[1] != nil {
			arg1 = args[1].(itemfile.IT2File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteIT2ItemFileData_Call) Return(err error) *MockFileEditorService_WriteIT2ItemFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteIT2ItemFileData_Call) RunAndReturn(run func(path string, data itemfile.IT2File) error) *MockFileEditorService_WriteIT2ItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteIT3ItemFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteIT3ItemFileData(path string, data itemfile.IT3File) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteIT3ItemFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, itemfile.IT3File) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteIT3ItemFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteIT3ItemFileData'
type MockFileEditorService_WriteIT3ItemFileData_Call struct {
	*mock.Call
}

// WriteIT3ItemFileData is a helper method to define mock.On call
//   - path string
//   - data itemfile.IT3File
func (_e *MockFileEditorService_Expecter) WriteIT3ItemFileData(path interface{}, data interface{}) *MockFileEditorService_WriteIT3ItemFileData_Call {
	return &MockFileEditorService_WriteIT3ItemFileData_Call{Call: _e.mock.On("WriteIT3ItemFileData", path, data)}
}

func (_c *MockFileEditorService_WriteIT3ItemFileData_Call) Run(run func(path string, data itemfile.IT3File)) *MockFileEditorService_WriteIT3ItemFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 itemfile.IT3File
		if args[1] != nil {
			arg1 = args[1].(itemfile.IT3File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteIT3ItemFileData_Call) Return(err error) *MockFileEditorService_WriteIT3ItemFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteIT3ItemFileData_Call) RunAndReturn(run func(path string, data itemfile.IT3File) error) *MockFileEditorService_WriteIT3ItemFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteItemCombinationData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteItemCombinationData(path string, data itemcombinationdata.ItemCombinationData) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteItemCombinationData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, itemcombinationdata.ItemCombinationData) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteItemCombinationData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteItemCombinationData'
type MockFileEditorService_WriteItemCombinationData_Call struct {
	*mock.Call
}

// WriteItemCombinationData is a helper method to define mock.On call
//   - path string
//   - data itemcombinationdata.ItemCombinationData
func (_e *MockFileEditorService_Expecter) WriteItemCombinationData(path interface{}, data interface{}) *MockFileEditorService_WriteItemCombinationData_Call {
	return &MockFileEditorService_WriteItemCombinationData_Call{Call: _e.mock.On("WriteItemCombinationData", path, data)}
}

func (_c *MockFileEditorService_WriteItemCombinationData_Call) Run(run func(path string, data itemcombinationdata.ItemCombinationData)) *MockFileEditorService_WriteItemCombinationData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 itemcombinationdata.ItemCombinationData
		if args[1] != nil {
			arg1 = args[1].(itemcombinationdata.ItemCombinationData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteItemCombinationData_Call) Return(err error) *MockFileEditorService_WriteItemCombinationData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteItemCombinationData_Call) RunAndReturn(run func(path string, data itemcombinationdata.ItemCombinationData) error) *MockFileEditorService_WriteItemCombinationData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteNPCFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteNPCFileData(path string, data *NPCFileData) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteNPCFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *NPCFileData) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteNPCFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteNPCFileData'
type MockFileEditorService_WriteNPCFileData_Call struct {
	*mock.Call
}

// WriteNPCFileData is a helper method to define mock.On call
//   - path string
//   - data *NPCFileData
func (_e *MockFileEditorService_Expecter) WriteNPCFileData(path interface{}, data interface{}) *MockFileEditorService_WriteNPCFileData_Call {
	return &MockFileEditorService_WriteNPCFileData_Call{Call: _e.mock.On("WriteNPCFileData", path, data)}
}

func (_c *MockFileEditorService_WriteNPCFileData_Call) Run(run func(path string, data *NPCFileData)) *MockFileEditorService_WriteNPCFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *NPCFileData
		if args[1] != nil {
			arg1 = args[1].(*NPCFileData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteNPCFileData_Call) Return(err error) *MockFileEditorService_WriteNPCFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteNPCFileData_Call) RunAndReturn(run func(path string, data *NPCFileData) error) *MockFileEditorService_WriteNPCFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteQuestFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteQuestFileData(path string, data questfile.QuestFile) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteQuestFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, questfile.QuestFile) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteQuestFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteQuestFileData'
type MockFileEditorService_WriteQuestFileData_Call struct {
	*mock.Call
}

// WriteQuestFileData is a helper method to define mock.On call
//   - path string
//   - data questfile.QuestFile
func (_e *MockFileEditorService_Expecter) WriteQuestFileData(path interface{}, data interface{}) *MockFileEditorService_WriteQuestFileData_Call {
	return &MockFileEditorService_WriteQuestFileData_Call{Call: _e.mock.On("WriteQuestFileData", path, data)}
}

func (_c *MockFileEditorService_WriteQuestFileData_Call) Run(run func(path string, data questfile.QuestFile)) *MockFileEditorService_WriteQuestFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 questfile.QuestFile
		if args[1] != nil {
			arg1 = args[1].(questfile.QuestFile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteQuestFileData_Call) Return(err error) *MockFileEditorService_WriteQuestFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteQuestFileData_Call) RunAndReturn(run func(path string, data questfile.QuestFile) error) *MockFileEditorService_WriteQuestFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteSpawnFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteSpawnFileData(path string, data []NPCSpawnData) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteSpawnFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []NPCSpawnData) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteSpawnFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteSpawnFileData'
type MockFileEditorService_WriteSpawnFileData_Call struct {
	*mock.Call
}

// WriteSpawnFileData is a helper method to define mock.On call
//   - path string
//   - data []NPCSpawnData
func (_e *MockFileEditorService_Expecter) WriteSpawnFileData(path interface{}, data interface{}) *MockFileEditorService_WriteSpawnFileData_Call {
	return &MockFileEditorService_WriteSpawnFileData_Call{Call: _e.mock.On("WriteSpawnFileData", path, data)}
}

func (_c *MockFileEditorService_WriteSpawnFileData_Call) Run(run func(path string, data []NPCSpawnData)) *MockFileEditorService_WriteSpawnFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []NPCSpawnData
		if args[1] != nil {
			arg1 = args[1].([]NPCSpawnData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteSpawnFileData_Call) Return(err error) *MockFileEditorService_WriteSpawnFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteSpawnFileData_Call) RunAndReturn(run func(path string, data []NPCSpawnData) error) *MockFileEditorService_WriteSpawnFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteTextFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteTextFileData(path string, content string, perm fs.FileMode) error {
	ret := _mock.Called(path, content, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteTextFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, fs.FileMode) error); ok {
		r0 = returnFunc(path, content, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteTextFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTextFileData'
type MockFileEditorService_WriteTextFileData_Call struct {
	*mock.Call
}

// WriteTextFileData is a helper method to define mock.On call
//   - path string
//   - content string
//   - perm fs.FileMode
func (_e *MockFileEditorService_Expecter) WriteTextFileData(path interface{}, content interface{}, perm interface{}) *MockFileEditorService_WriteTextFileData_Call {
	return &MockFileEditorService_WriteTextFileData_Call{Call: _e.mock.On("WriteTextFileData", path, content, perm)}
}

func (_c *MockFileEditorService_WriteTextFileData_Call) Run(run func(path string, content string, perm fs.FileMode)) *MockFileEditorService_WriteTextFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteTextFileData_Call) Return(err error) *MockFileEditorService_WriteTextFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteTextFileData_Call) RunAndReturn(run func(path string, content string, perm fs.FileMode) error) *MockFileEditorService_WriteTextFileData_Call {
	_c.Call.Return(run)
	return _c
}
