// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/omnihance/omnihance-a3-agent/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackupService creates a new instance of MockBackupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackupService {
	mock := &MockBackupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackupService is an autogenerated mock type for the BackupService type
type MockBackupService struct {
	mock.Mock
}

type MockBackupService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackupService) EXPECT() *MockBackupService_Expecter {
	return &MockBackupService_Expecter{mock: &_m.Mock}
}

// CancelJob provides a mock function for the type MockBackupService
func (_mock *MockBackupService) CancelJob(ctx context.Context, id int64) (*db.BackupRun, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelJob")
	}

	var r0 *db.BackupRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*db.BackupRun, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *db.BackupRun); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BackupRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupService_CancelJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelJob'
type MockBackupService_CancelJob_Call struct {
	*mock.Call
}

// CancelJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockBackupService_Expecter) CancelJob(ctx interface{}, id interface{}) *MockBackupService_CancelJob_Call {
	return &MockBackupService_CancelJob_Call{Call: _e.mock.On("CancelJob", ctx, id)}
}

func (_c *MockBackupService_CancelJob_Call) Run(run func(ctx context.Context, id int64)) *MockBackupService_CancelJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupService_CancelJob_Call) Return(backupRun *db.BackupRun, err error) *MockBackupService_CancelJob_Call {
	_c.Call.Return(backupRun, err)
	return _c
}

func (_c *MockBackupService_CancelJob_Call) RunAndReturn(run func(ctx context.Context, id int64) (*db.BackupRun, error)) *MockBackupService_CancelJob_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJob provides a mock function for the type MockBackupService
func (_mock *MockBackupService) CreateJob(ctx context.Context, payload db.BackupJobPayload, userID *int64) (*db.BackupJob, error) {
	ret := _mock.Called(ctx, payload, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 *db.BackupJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.BackupJobPayload, *int64) (*db.BackupJob, error)); ok {
		return returnFunc(ctx, payload, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.BackupJobPayload, *int64) *db.BackupJob); ok {
		r0 = returnFunc(ctx, payload, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BackupJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.BackupJobPayload, *int64) error); ok {
		r1 = returnFunc(ctx, payload, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupService_CreateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJob'
type MockBackupService_CreateJob_Call struct {
	*mock.Call
}

// CreateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - payload db.BackupJobPayload
//   - userID *int64
func (_e *MockBackupService_Expecter) CreateJob(ctx interface{}, payload interface{}, userID interface{}) *MockBackupService_CreateJob_Call {
	return &MockBackupService_CreateJob_Call{Call: _e.mock.On("CreateJob", ctx, payload, userID)}
}

func (_c *MockBackupService_CreateJob_Call) Run(run func(ctx context.Context, payload db.BackupJobPayload, userID *int64)) *MockBackupService_CreateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.BackupJobPayload
		if args[1] != nil {
			arg1 = args[1].(db.BackupJobPayload)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackupService_CreateJob_Call) Return(backupJob *db.BackupJob, err error) *MockBackupService_CreateJob_Call {
	_c.Call.Return(backupJob, err)
	return _c
}

func (_c *MockBackupService_CreateJob_Call) RunAndReturn(run func(ctx context.Context, payload db.BackupJobPayload, userID *int64) (*db.BackupJob, error)) *MockBackupService_CreateJob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJob provides a mock function for the type MockBackupService
func (_mock *MockBackupService) DeleteJob(ctx context.Context, id int64, userID *int64) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *int64) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackupService_DeleteJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJob'
type MockBackupService_DeleteJob_Call struct {
	*mock.Call
}

// DeleteJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - userID *int64
func (_e *MockBackupService_Expecter) DeleteJob(ctx interface{}, id interface{}, userID interface{}) *MockBackupService_DeleteJob_Call {
	return &MockBackupService_DeleteJob_Call{Call: _e.mock.On("DeleteJob", ctx, id, userID)}
}

func (_c *MockBackupService_DeleteJob_Call) Run(run func(ctx context.Context, id int64, userID *int64)) *MockBackupService_DeleteJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackupService_DeleteJob_Call) Return(err error) *MockBackupService_DeleteJob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackupService_DeleteJob_Call) RunAndReturn(run func(ctx context.Context, id int64, userID *int64) error) *MockBackupService_DeleteJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetJob provides a mock function for the type MockBackupService
func (_mock *MockBackupService) GetJob(id int64) (*db.BackupJob, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 *db.BackupJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*db.BackupJob, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *db.BackupJob); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BackupJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupService_GetJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJob'
type MockBackupService_GetJob_Call struct {
	*mock.Call
}

// GetJob is a helper method to define mock.On call
//   - id int64
func (_e *MockBackupService_Expecter) GetJob(id interface{}) *MockBackupService_GetJob_Call {
	return &MockBackupService_GetJob_Call{Call: _e.mock.On("GetJob", id)}
}

func (_c *MockBackupService_GetJob_Call) Run(run func(id int64)) *MockBackupService_GetJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackupService_GetJob_Call) Return(backupJob *db.BackupJob, err error) *MockBackupService_GetJob_Call {
	_c.Call.Return(backupJob, err)
	return _c
}

func (_c *MockBackupService_GetJob_Call) RunAndReturn(run func(id int64) (*db.BackupJob, error)) *MockBackupService_GetJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobs provides a mock function for the type MockBackupService
func (_mock *MockBackupService) GetJobs() ([]db.BackupJob, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJobs")
	}

	var r0 []db.BackupJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]db.BackupJob, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []db.BackupJob); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.BackupJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupService_GetJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobs'
type MockBackupService_GetJobs_Call struct {
	*mock.Call
}

// GetJobs is a helper method to define mock.On call
func (_e *MockBackupService_Expecter) GetJobs() *MockBackupService_GetJobs_Call {
	return &MockBackupService_GetJobs_Call{Call: _e.mock.On("GetJobs")}
}

func (_c *MockBackupService_GetJobs_Call) Run(run func()) *MockBackupService_GetJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackupService_GetJobs_Call) Return(backupJobs []db.BackupJob, err error) *MockBackupService_GetJobs_Call {
	_c.Call.Return(backupJobs, err)
	return _c
}

func (_c *MockBackupService_GetJobs_Call) RunAndReturn(run func() ([]db.BackupJob, error)) *MockBackupService_GetJobs_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunDetails provides a mock function for the type MockBackupService
func (_mock *MockBackupService) GetRunDetails(runID int64) (*BackupRunDetails, error) {
	ret := _mock.Called(runID)

	if len(ret) == 0 {
		panic("no return value specified for GetRunDetails")
	}

	var r0 *BackupRunDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*BackupRunDetails, error)); ok {
		return returnFunc(runID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *BackupRunDetails); ok {
		r0 = returnFunc(runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*BackupRunDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(runID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupService_GetRunDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunDetails'
type MockBackupService_GetRunDetails_Call struct {
	*mock.Call
}

// GetRunDetails is a helper method to define mock.On call
//   - runID int64
func (_e *MockBackupService_Expecter) GetRunDetails(runID interface{}) *MockBackupService_GetRunDetails_Call {
	return &MockBackupService_GetRunDetails_Call{Call: _e.mock.On("GetRunDetails", runID)}
}

func (_c *MockBackupService_GetRunDetails_Call) Run(run func(runID int64)) *MockBackupService_GetRunDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackupService_GetRunDetails_Call) Return(backupRunDetails *BackupRunDetails, err error) *MockBackupService_GetRunDetails_Call {
	_c.Call.Return(backupRunDetails, err)
	return _c
}

func (_c *MockBackupService_GetRunDetails_Call) RunAndReturn(run func(runID int64) (*BackupRunDetails, error)) *MockBackupService_GetRunDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunFile provides a mock function for the type MockBackupService
func (_mock *MockBackupService) GetRunFile(fileID int64) (*db.BackupRunFile, error) {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetRunFile")
	}

	var r0 *db.BackupRunFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*db.BackupRunFile, error)); ok {
		return returnFunc(fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *db.BackupRunFile); ok {
		r0 = returnFunc(fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BackupRunFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupService_GetRunFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunFile'
type MockBackupService_GetRunFile_Call struct {
	*mock.Call
}

// GetRunFile is a helper method to define mock.On call
//   - fileID int64
func (_e *MockBackupService_Expecter) GetRunFile(fileID interface{}) *MockBackupService_GetRunFile_Call {
	return &MockBackupService_GetRunFile_Call{Call: _e.mock.On("GetRunFile", fileID)}
}

func (_c *MockBackupService_GetRunFile_Call) Run(run func(fileID int64)) *MockBackupService_GetRunFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackupService_GetRunFile_Call) Return(backupRunFile *db.BackupRunFile, err error) *MockBackupService_GetRunFile_Call {
	_c.Call.Return(backupRunFile, err)
	return _c
}

func (_c *MockBackupService_GetRunFile_Call) RunAndReturn(run func(fileID int64) (*db.BackupRunFile, error)) *MockBackupService_GetRunFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetRuns provides a mock function for the type MockBackupService
func (_mock *MockBackupService) GetRuns(jobID int64, page int, pageSize int) ([]db.BackupRun, int64, error) {
	ret := _mock.Called(jobID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetRuns")
	}

	var r0 []db.BackupRun
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int64, int, int) ([]db.BackupRun, int64, error)); ok {
		return returnFunc(jobID, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int, int) []db.BackupRun); ok {
		r0 = returnFunc(jobID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.BackupRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int, int) int64); ok {
		r1 = returnFunc(jobID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(int64, int, int) error); ok {
		r2 = returnFunc(jobID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBackupService_GetRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRuns'
type MockBackupService_GetRuns_Call struct {
	*mock.Call
}

// GetRuns is a helper method to define mock.On call
//   - jobID int64
//   - page int
//   - pageSize int
func (_e *MockBackupService_Expecter) GetRuns(jobID interface{}, page interface{}, pageSize interface{}) *MockBackupService_GetRuns_Call {
	return &MockBackupService_GetRuns_Call{Call: _e.mock.On("GetRuns", jobID, page, pageSize)}
}

func (_c *MockBackupService_GetRuns_Call) Run(run func(jobID int64, page int, pageSize int)) *MockBackupService_GetRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackupService_GetRuns_Call) Return(backupRuns []db.BackupRun, n int64, err error) *MockBackupService_GetRuns_Call {
	_c.Call.Return(backupRuns, n, err)
	return _c
}

func (_c *MockBackupService_GetRuns_Call) RunAndReturn(run func(jobID int64, page int, pageSize int) ([]db.BackupRun, int64, error)) *MockBackupService_GetRuns_Call {
	_c.Call.Return(run)
	return _c
}

// GetSQLServerDefaults provides a mock function for the type MockBackupService
func (_mock *MockBackupService) GetSQLServerDefaults() SQLServerBackupDefaults {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSQLServerDefaults")
	}

	var r0 SQLServerBackupDefaults
	if returnFunc, ok := ret.Get(0).(func() SQLServerBackupDefaults); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(SQLServerBackupDefaults)
	}
	return r0
}

// MockBackupService_GetSQLServerDefaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSQLServerDefaults'
type MockBackupService_GetSQLServerDefaults_Call struct {
	*mock.Call
}

// GetSQLServerDefaults is a helper method to define mock.On call
func (_e *MockBackupService_Expecter) GetSQLServerDefaults() *MockBackupService_GetSQLServerDefaults_Call {
	return &MockBackupService_GetSQLServerDefaults_Call{Call: _e.mock.On("GetSQLServerDefaults")}
}

func (_c *MockBackupService_GetSQLServerDefaults_Call) Run(run func()) *MockBackupService_GetSQLServerDefaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackupService_GetSQLServerDefaults_Call) Return(sQLServerBackupDefaults SQLServerBackupDefaults) *MockBackupService_GetSQLServerDefaults_Call {
	_c.Call.Return(sQLServerBackupDefaults)
	return _c
}

func (_c *MockBackupService_GetSQLServerDefaults_Call) RunAndReturn(run func() SQLServerBackupDefaults) *MockBackupService_GetSQLServerDefaults_Call {
	_c.Call.Return(run)
	return _c
}

// RunJob provides a mock function for the type MockBackupService
func (_mock *MockBackupService) RunJob(ctx context.Context, id int64, triggerType string, userID *int64) (*db.BackupRun, error) {
	ret := _mock.Called(ctx, id, triggerType, userID)

	if len(ret) == 0 {
		panic("no return value specified for RunJob")
	}

	var r0 *db.BackupRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, *int64) (*db.BackupRun, error)); ok {
		return returnFunc(ctx, id, triggerType, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, *int64) *db.BackupRun); ok {
		r0 = returnFunc(ctx, id, triggerType, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BackupRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, *int64) error); ok {
		r1 = returnFunc(ctx, id, triggerType, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupService_RunJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunJob'
type MockBackupService_RunJob_Call struct {
	*mock.Call
}

// RunJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - triggerType string
//   - userID *int64
func (_e *MockBackupService_Expecter) RunJob(ctx interface{}, id interface{}, triggerType interface{}, userID interface{}) *MockBackupService_RunJob_Call {
	return &MockBackupService_RunJob_Call{Call: _e.mock.On("RunJob", ctx, id, triggerType, userID)}
}

func (_c *MockBackupService_RunJob_Call) Run(run func(ctx context.Context, id int64, triggerType string, userID *int64)) *MockBackupService_RunJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackupService_RunJob_Call) Return(backupRun *db.BackupRun, err error) *MockBackupService_RunJob_Call {
	_c.Call.Return(backupRun, err)
	return _c
}

func (_c *MockBackupService_RunJob_Call) RunAndReturn(run func(ctx context.Context, id int64, triggerType string, userID *int64) (*db.BackupRun, error)) *MockBackupService_RunJob_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPaths provides a mock function for the type MockBackupService
func (_mock *MockBackupService) SearchPaths(query string, kind string) ([]PathSearchResult, error) {
	ret := _mock.Called(query, kind)

	if len(ret) == 0 {
		panic("no return value specified for SearchPaths")
	}

	var r0 []PathSearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]PathSearchResult, error)); ok {
		return returnFunc(query, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []PathSearchResult); ok {
		r0 = returnFunc(query, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PathSearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(query, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupService_SearchPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPaths'
type MockBackupService_SearchPaths_Call struct {
	*mock.Call
}

// SearchPaths is a helper method to define mock.On call
//   - query string
//   - kind string
func (_e *MockBackupService_Expecter) SearchPaths(query interface{}, kind interface{}) *MockBackupService_SearchPaths_Call {
	return &MockBackupService_SearchPaths_Call{Call: _e.mock.On("SearchPaths", query, kind)}
}

func (_c *MockBackupService_SearchPaths_Call) Run(run func(query string, kind string)) *MockBackupService_SearchPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupService_SearchPaths_Call) Return(pathSearchResults []PathSearchResult, err error) *MockBackupService_SearchPaths_Call {
	_c.Call.Return(pathSearchResults, err)
	return _c
}

func (_c *MockBackupService_SearchPaths_Call) RunAndReturn(run func(query string, kind string) ([]PathSearchResult, error)) *MockBackupService_SearchPaths_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockBackupService
func (_mock *MockBackupService) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackupService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockBackupService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockBackupService_Expecter) Start() *MockBackupService_Start_Call {
	return &MockBackupService_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockBackupService_Start_Call) Run(run func()) *MockBackupService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackupService_Start_Call) Return(err error) *MockBackupService_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackupService_Start_Call) RunAndReturn(run func() error) *MockBackupService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockBackupService
func (_mock *MockBackupService) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackupService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockBackupService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockBackupService_Expecter) Stop() *MockBackupService_Stop_Call {
	return &MockBackupService_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockBackupService_Stop_Call) Run(run func()) *MockBackupService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackupService_Stop_Call) Return(err error) *MockBackupService_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackupService_Stop_Call) RunAndReturn(run func() error) *MockBackupService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJob provides a mock function for the type MockBackupService
func (_mock *MockBackupService) UpdateJob(ctx context.Context, id int64, payload db.BackupJobPayload, userID *int64) (*db.BackupJob, error) {
	ret := _mock.Called(ctx, id, payload, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJob")
	}

	var r0 *db.BackupJob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, db.BackupJobPayload, *int64) (*db.BackupJob, error)); ok {
		return returnFunc(ctx, id, payload, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, db.BackupJobPayload, *int64) *db.BackupJob); ok {
		r0 = returnFunc(ctx, id, payload, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.BackupJob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, db.BackupJobPayload, *int64) error); ok {
		r1 = returnFunc(ctx, id, payload, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackupService_UpdateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJob'
type MockBackupService_UpdateJob_Call struct {
	*mock.Call
}

// UpdateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - payload db.BackupJobPayload
//   - userID *int64
func (_e *MockBackupService_Expecter) UpdateJob(ctx interface{}, id interface{}, payload interface{}, userID interface{}) *MockBackupService_UpdateJob_Call {
	return &MockBackupService_UpdateJob_Call{Call: _e.mock.On("UpdateJob", ctx, id, payload, userID)}
}

func (_c *MockBackupService_UpdateJob_Call) Run(run func(ctx context.Context, id int64, payload db.BackupJobPayload, userID *int64)) *MockBackupService_UpdateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 db.BackupJobPayload
		if args[2] != nil {
			arg2 = args[2].(db.BackupJobPayload)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackupService_UpdateJob_Call) Return(backupJob *db.BackupJob, err error) *MockBackupService_UpdateJob_Call {
	_c.Call.Return(backupJob, err)
	return _c
}

func (_c *MockBackupService_UpdateJob_Call) RunAndReturn(run func(ctx context.Context, id int64, payload db.BackupJobPayload, userID *int64) (*db.BackupJob, error)) *MockBackupService_UpdateJob_Call {
	_c.Call.Return(run)
	return _c
}
