// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVersionCheckerService creates a new instance of MockVersionCheckerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionCheckerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionCheckerService {
	mock := &MockVersionCheckerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVersionCheckerService is an autogenerated mock type for the VersionCheckerService type
type MockVersionCheckerService struct {
	mock.Mock
}

type MockVersionCheckerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionCheckerService) EXPECT() *MockVersionCheckerService_Expecter {
	return &MockVersionCheckerService_Expecter{mock: &_m.Mock}
}

// CheckNow provides a mock function for the type MockVersionCheckerService
func (_mock *MockVersionCheckerService) CheckNow(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckNow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVersionCheckerService_CheckNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNow'
type MockVersionCheckerService_CheckNow_Call struct {
	*mock.Call
}

// CheckNow is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVersionCheckerService_Expecter) CheckNow(ctx interface{}) *MockVersionCheckerService_CheckNow_Call {
	return &MockVersionCheckerService_CheckNow_Call{Call: _e.mock.On("CheckNow", ctx)}
}

func (_c *MockVersionCheckerService_CheckNow_Call) Run(run func(ctx context.Context)) *MockVersionCheckerService_CheckNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionCheckerService_CheckNow_Call) Return(err error) *MockVersionCheckerService_CheckNow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVersionCheckerService_CheckNow_Call) RunAndReturn(run func(ctx context.Context) error) *MockVersionCheckerService_CheckNow_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockVersionCheckerService
func (_mock *MockVersionCheckerService) GetStatus() VersionCheckStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 VersionCheckStatus
	if returnFunc, ok := ret.Get(0).(func() VersionCheckStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(VersionCheckStatus)
	}
	return r0
}

// MockVersionCheckerService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockVersionCheckerService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *MockVersionCheckerService_Expecter) GetStatus() *MockVersionCheckerService_GetStatus_Call {
	return &MockVersionCheckerService_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *MockVersionCheckerService_GetStatus_Call) Run(run func()) *MockVersionCheckerService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersionCheckerService_GetStatus_Call) Return(versionCheckStatus VersionCheckStatus) *MockVersionCheckerService_GetStatus_Call {
	_c.Call.Return(versionCheckStatus)
	return _c
}

func (_c *MockVersionCheckerService_GetStatus_Call) RunAndReturn(run func() VersionCheckStatus) *MockVersionCheckerService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockVersionCheckerService
func (_mock *MockVersionCheckerService) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVersionCheckerService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockVersionCheckerService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockVersionCheckerService_Expecter) Start() *MockVersionCheckerService_Start_Call {
	return &MockVersionCheckerService_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockVersionCheckerService_Start_Call) Run(run func()) *MockVersionCheckerService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersionCheckerService_Start_Call) Return(err error) *MockVersionCheckerService_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVersionCheckerService_Start_Call) RunAndReturn(run func() error) *MockVersionCheckerService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockVersionCheckerService
func (_mock *MockVersionCheckerService) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVersionCheckerService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockVersionCheckerService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockVersionCheckerService_Expecter) Stop() *MockVersionCheckerService_Stop_Call {
	return &MockVersionCheckerService_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockVersionCheckerService_Stop_Call) Run(run func()) *MockVersionCheckerService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersionCheckerService_Stop_Call) Return(err error) *MockVersionCheckerService_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVersionCheckerService_Stop_Call) RunAndReturn(run func() error) *MockVersionCheckerService_Stop_Call {
	_c.Call.Return(run)
	return _c
}
