// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"io/fs"
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileEditorService creates a new instance of MockFileEditorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileEditorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileEditorService {
	mock := &MockFileEditorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileEditorService is an autogenerated mock type for the FileEditorService type
type MockFileEditorService struct {
	mock.Mock
}

type MockFileEditorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileEditorService) EXPECT() *MockFileEditorService_Expecter {
	return &MockFileEditorService_Expecter{mock: &_m.Mock}
}

// GetFileAPIEndpoint provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) GetFileAPIEndpoint(path string, fileInfo fs.FileInfo) string {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetFileAPIEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) string); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFileEditorService_GetFileAPIEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileAPIEndpoint'
type MockFileEditorService_GetFileAPIEndpoint_Call struct {
	*mock.Call
}

// GetFileAPIEndpoint is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) GetFileAPIEndpoint(path interface{}, fileInfo interface{}) *MockFileEditorService_GetFileAPIEndpoint_Call {
	return &MockFileEditorService_GetFileAPIEndpoint_Call{Call: _e.mock.On("GetFileAPIEndpoint", path, fileInfo)}
}

func (_c *MockFileEditorService_GetFileAPIEndpoint_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_GetFileAPIEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_GetFileAPIEndpoint_Call) Return(s string) *MockFileEditorService_GetFileAPIEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFileEditorService_GetFileAPIEndpoint_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) string) *MockFileEditorService_GetFileAPIEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileType provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) GetFileType(path string, fileInfo fs.FileInfo) FileType {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetFileType")
	}

	var r0 FileType
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) FileType); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(FileType)
	}
	return r0
}

// MockFileEditorService_GetFileType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileType'
type MockFileEditorService_GetFileType_Call struct {
	*mock.Call
}

// GetFileType is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) GetFileType(path interface{}, fileInfo interface{}) *MockFileEditorService_GetFileType_Call {
	return &MockFileEditorService_GetFileType_Call{Call: _e.mock.On("GetFileType", path, fileInfo)}
}

func (_c *MockFileEditorService_GetFileType_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_GetFileType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_GetFileType_Call) Return(fileType FileType) *MockFileEditorService_GetFileType_Call {
	_c.Call.Return(fileType)
	return _c
}

func (_c *MockFileEditorService_GetFileType_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) FileType) *MockFileEditorService_GetFileType_Call {
	_c.Call.Return(run)
	return _c
}

// Hostname provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) Hostname() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hostname")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_Hostname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hostname'
type MockFileEditorService_Hostname_Call struct {
	*mock.Call
}

// Hostname is a helper method to define mock.On call
func (_e *MockFileEditorService_Expecter) Hostname() *MockFileEditorService_Hostname_Call {
	return &MockFileEditorService_Hostname_Call{Call: _e.mock.On("Hostname")}
}

func (_c *MockFileEditorService_Hostname_Call) Run(run func()) *MockFileEditorService_Hostname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileEditorService_Hostname_Call) Return(s string, err error) *MockFileEditorService_Hostname_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileEditorService_Hostname_Call) RunAndReturn(run func() (string, error)) *MockFileEditorService_Hostname_Call {
	_c.Call.Return(run)
	return _c
}

// IsExist provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsExist(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsExist")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExist'
type MockFileEditorService_IsExist_Call struct {
	*mock.Call
}

// IsExist is a helper method to define mock.On call
//   - err error
func (_e *MockFileEditorService_Expecter) IsExist(err interface{}) *MockFileEditorService_IsExist_Call {
	return &MockFileEditorService_IsExist_Call{Call: _e.mock.On("IsExist", err)}
}

func (_c *MockFileEditorService_IsExist_Call) Run(run func(err error)) *MockFileEditorService_IsExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsExist_Call) Return(b bool) *MockFileEditorService_IsExist_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsExist_Call) RunAndReturn(run func(err error) bool) *MockFileEditorService_IsExist_Call {
	_c.Call.Return(run)
	return _c
}

// IsFileEditable provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsFileEditable(path string, fileInfo fs.FileInfo) bool {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for IsFileEditable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) bool); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsFileEditable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFileEditable'
type MockFileEditorService_IsFileEditable_Call struct {
	*mock.Call
}

// IsFileEditable is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) IsFileEditable(path interface{}, fileInfo interface{}) *MockFileEditorService_IsFileEditable_Call {
	return &MockFileEditorService_IsFileEditable_Call{Call: _e.mock.On("IsFileEditable", path, fileInfo)}
}

func (_c *MockFileEditorService_IsFileEditable_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_IsFileEditable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsFileEditable_Call) Return(b bool) *MockFileEditorService_IsFileEditable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsFileEditable_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) bool) *MockFileEditorService_IsFileEditable_Call {
	_c.Call.Return(run)
	return _c
}

// IsFileViewable provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsFileViewable(path string, fileInfo fs.FileInfo) bool {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for IsFileViewable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) bool); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsFileViewable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFileViewable'
type MockFileEditorService_IsFileViewable_Call struct {
	*mock.Call
}

// IsFileViewable is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) IsFileViewable(path interface{}, fileInfo interface{}) *MockFileEditorService_IsFileViewable_Call {
	return &MockFileEditorService_IsFileViewable_Call{Call: _e.mock.On("IsFileViewable", path, fileInfo)}
}

func (_c *MockFileEditorService_IsFileViewable_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_IsFileViewable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsFileViewable_Call) Return(b bool) *MockFileEditorService_IsFileViewable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsFileViewable_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) bool) *MockFileEditorService_IsFileViewable_Call {
	_c.Call.Return(run)
	return _c
}

// IsNotExist provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsNotExist(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsNotExist")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsNotExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNotExist'
type MockFileEditorService_IsNotExist_Call struct {
	*mock.Call
}

// IsNotExist is a helper method to define mock.On call
//   - err error
func (_e *MockFileEditorService_Expecter) IsNotExist(err interface{}) *MockFileEditorService_IsNotExist_Call {
	return &MockFileEditorService_IsNotExist_Call{Call: _e.mock.On("IsNotExist", err)}
}

func (_c *MockFileEditorService_IsNotExist_Call) Run(run func(err error)) *MockFileEditorService_IsNotExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsNotExist_Call) Return(b bool) *MockFileEditorService_IsNotExist_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsNotExist_Call) RunAndReturn(run func(err error) bool) *MockFileEditorService_IsNotExist_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) MkdirAll(path string, perm fs.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileEditorService_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm fs.FileMode
func (_e *MockFileEditorService_Expecter) MkdirAll(path interface{}, perm interface{}) *MockFileEditorService_MkdirAll_Call {
	return &MockFileEditorService_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFileEditorService_MkdirAll_Call) Run(run func(path string, perm fs.FileMode)) *MockFileEditorService_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileMode
		if args[1] != nil {
			arg1 = args[1].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_MkdirAll_Call) Return(err error) *MockFileEditorService_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_MkdirAll_Call) RunAndReturn(run func(path string, perm fs.FileMode) error) *MockFileEditorService_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) OpenFile(name string, flag int, perm fs.FileMode) (*os.File, error) {
	ret := _mock.Called(name, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, fs.FileMode) (*os.File, error)); ok {
		return returnFunc(name, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, fs.FileMode) *os.File); ok {
		r0 = returnFunc(name, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, fs.FileMode) error); ok {
		r1 = returnFunc(name, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type MockFileEditorService_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - name string
//   - flag int
//   - perm fs.FileMode
func (_e *MockFileEditorService_Expecter) OpenFile(name interface{}, flag interface{}, perm interface{}) *MockFileEditorService_OpenFile_Call {
	return &MockFileEditorService_OpenFile_Call{Call: _e.mock.On("OpenFile", name, flag, perm)}
}

func (_c *MockFileEditorService_OpenFile_Call) Run(run func(name string, flag int, perm fs.FileMode)) *MockFileEditorService_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileEditorService_OpenFile_Call) Return(file *os.File, err error) *MockFileEditorService_OpenFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileEditorService_OpenFile_Call) RunAndReturn(run func(name string, flag int, perm fs.FileMode) (*os.File, error)) *MockFileEditorService_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadDir(name string) ([]fs.DirEntry, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockFileEditorService_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *MockFileEditorService_Expecter) ReadDir(name interface{}) *MockFileEditorService_ReadDir_Call {
	return &MockFileEditorService_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *MockFileEditorService_ReadDir_Call) Run(run func(name string)) *MockFileEditorService_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadDir_Call) Return(dirEntrys []fs.DirEntry, err error) *MockFileEditorService_ReadDir_Call {
	_c.Call.Return(dirEntrys, err)
	return _c
}

func (_c *MockFileEditorService_ReadDir_Call) RunAndReturn(run func(name string) ([]fs.DirEntry, error)) *MockFileEditorService_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadFile(name string) ([]byte, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFileEditorService_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name string
func (_e *MockFileEditorService_Expecter) ReadFile(name interface{}) *MockFileEditorService_ReadFile_Call {
	return &MockFileEditorService_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *MockFileEditorService_ReadFile_Call) Run(run func(name string)) *MockFileEditorService_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadFile_Call) Return(bytes []byte, err error) *MockFileEditorService_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockFileEditorService_ReadFile_Call) RunAndReturn(run func(name string) ([]byte, error)) *MockFileEditorService_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReadNPCFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadNPCFileData(path string) (*NPCFileData, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadNPCFileData")
	}

	var r0 *NPCFileData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*NPCFileData, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *NPCFileData); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NPCFileData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadNPCFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadNPCFileData'
type MockFileEditorService_ReadNPCFileData_Call struct {
	*mock.Call
}

// ReadNPCFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadNPCFileData(path interface{}) *MockFileEditorService_ReadNPCFileData_Call {
	return &MockFileEditorService_ReadNPCFileData_Call{Call: _e.mock.On("ReadNPCFileData", path)}
}

func (_c *MockFileEditorService_ReadNPCFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadNPCFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadNPCFileData_Call) Return(nPCFileData *NPCFileData, err error) *MockFileEditorService_ReadNPCFileData_Call {
	_c.Call.Return(nPCFileData, err)
	return _c
}

func (_c *MockFileEditorService_ReadNPCFileData_Call) RunAndReturn(run func(path string) (*NPCFileData, error)) *MockFileEditorService_ReadNPCFileData_Call {
	_c.Call.Return(run)
	return _c
}

// ReadSpawnFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadSpawnFileData(path string) ([]NPCSpawnData, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadSpawnFileData")
	}

	var r0 []NPCSpawnData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]NPCSpawnData, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []NPCSpawnData); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]NPCSpawnData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadSpawnFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadSpawnFileData'
type MockFileEditorService_ReadSpawnFileData_Call struct {
	*mock.Call
}

// ReadSpawnFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadSpawnFileData(path interface{}) *MockFileEditorService_ReadSpawnFileData_Call {
	return &MockFileEditorService_ReadSpawnFileData_Call{Call: _e.mock.On("ReadSpawnFileData", path)}
}

func (_c *MockFileEditorService_ReadSpawnFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadSpawnFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadSpawnFileData_Call) Return(nPCSpawnDatas []NPCSpawnData, err error) *MockFileEditorService_ReadSpawnFileData_Call {
	_c.Call.Return(nPCSpawnDatas, err)
	return _c
}

func (_c *MockFileEditorService_ReadSpawnFileData_Call) RunAndReturn(run func(path string) ([]NPCSpawnData, error)) *MockFileEditorService_ReadSpawnFileData_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) Remove(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockFileEditorService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name string
func (_e *MockFileEditorService_Expecter) Remove(name interface{}) *MockFileEditorService_Remove_Call {
	return &MockFileEditorService_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *MockFileEditorService_Remove_Call) Run(run func(name string)) *MockFileEditorService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_Remove_Call) Return(err error) *MockFileEditorService_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_Remove_Call) RunAndReturn(run func(name string) error) *MockFileEditorService_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) RemoveAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockFileEditorService_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) RemoveAll(path interface{}) *MockFileEditorService_RemoveAll_Call {
	return &MockFileEditorService_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *MockFileEditorService_RemoveAll_Call) Run(run func(path string)) *MockFileEditorService_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_RemoveAll_Call) Return(err error) *MockFileEditorService_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_RemoveAll_Call) RunAndReturn(run func(path string) error) *MockFileEditorService_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) Stat(name string) (fs.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFileEditorService_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *MockFileEditorService_Expecter) Stat(name interface{}) *MockFileEditorService_Stat_Call {
	return &MockFileEditorService_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockFileEditorService_Stat_Call) Run(run func(name string)) *MockFileEditorService_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_Stat_Call) Return(fileInfo fs.FileInfo, err error) *MockFileEditorService_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockFileEditorService_Stat_Call) RunAndReturn(run func(name string) (fs.FileInfo, error)) *MockFileEditorService_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteFile(name string, data []byte, perm fs.FileMode) error {
	ret := _mock.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, fs.FileMode) error); ok {
		r0 = returnFunc(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockFileEditorService_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name string
//   - data []byte
//   - perm fs.FileMode
func (_e *MockFileEditorService_Expecter) WriteFile(name interface{}, data interface{}, perm interface{}) *MockFileEditorService_WriteFile_Call {
	return &MockFileEditorService_WriteFile_Call{Call: _e.mock.On("WriteFile", name, data, perm)}
}

func (_c *MockFileEditorService_WriteFile_Call) Run(run func(name string, data []byte, perm fs.FileMode)) *MockFileEditorService_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteFile_Call) Return(err error) *MockFileEditorService_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteFile_Call) RunAndReturn(run func(name string, data []byte, perm fs.FileMode) error) *MockFileEditorService_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteNPCFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteNPCFileData(path string, data *NPCFileData) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteNPCFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *NPCFileData) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteNPCFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteNPCFileData'
type MockFileEditorService_WriteNPCFileData_Call struct {
	*mock.Call
}

// WriteNPCFileData is a helper method to define mock.On call
//   - path string
//   - data *NPCFileData
func (_e *MockFileEditorService_Expecter) WriteNPCFileData(path interface{}, data interface{}) *MockFileEditorService_WriteNPCFileData_Call {
	return &MockFileEditorService_WriteNPCFileData_Call{Call: _e.mock.On("WriteNPCFileData", path, data)}
}

func (_c *MockFileEditorService_WriteNPCFileData_Call) Run(run func(path string, data *NPCFileData)) *MockFileEditorService_WriteNPCFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *NPCFileData
		if args[1] != nil {
			arg1 = args[1].(*NPCFileData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteNPCFileData_Call) Return(err error) *MockFileEditorService_WriteNPCFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteNPCFileData_Call) RunAndReturn(run func(path string, data *NPCFileData) error) *MockFileEditorService_WriteNPCFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteSpawnFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteSpawnFileData(path string, data []NPCSpawnData) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteSpawnFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []NPCSpawnData) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteSpawnFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteSpawnFileData'
type MockFileEditorService_WriteSpawnFileData_Call struct {
	*mock.Call
}

// WriteSpawnFileData is a helper method to define mock.On call
//   - path string
//   - data []NPCSpawnData
func (_e *MockFileEditorService_Expecter) WriteSpawnFileData(path interface{}, data interface{}) *MockFileEditorService_WriteSpawnFileData_Call {
	return &MockFileEditorService_WriteSpawnFileData_Call{Call: _e.mock.On("WriteSpawnFileData", path, data)}
}

func (_c *MockFileEditorService_WriteSpawnFileData_Call) Run(run func(path string, data []NPCSpawnData)) *MockFileEditorService_WriteSpawnFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []NPCSpawnData
		if args[1] != nil {
			arg1 = args[1].([]NPCSpawnData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteSpawnFileData_Call) Return(err error) *MockFileEditorService_WriteSpawnFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteSpawnFileData_Call) RunAndReturn(run func(path string, data []NPCSpawnData) error) *MockFileEditorService_WriteSpawnFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteTextFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteTextFileData(path string, content string) error {
	ret := _mock.Called(path, content)

	if len(ret) == 0 {
		panic("no return value specified for WriteTextFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(path, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteTextFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTextFileData'
type MockFileEditorService_WriteTextFileData_Call struct {
	*mock.Call
}

// WriteTextFileData is a helper method to define mock.On call
//   - path string
//   - content string
func (_e *MockFileEditorService_Expecter) WriteTextFileData(path interface{}, content interface{}) *MockFileEditorService_WriteTextFileData_Call {
	return &MockFileEditorService_WriteTextFileData_Call{Call: _e.mock.On("WriteTextFileData", path, content)}
}

func (_c *MockFileEditorService_WriteTextFileData_Call) Run(run func(path string, content string)) *MockFileEditorService_WriteTextFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteTextFileData_Call) Return(err error) *MockFileEditorService_WriteTextFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteTextFileData_Call) RunAndReturn(run func(path string, content string) error) *MockFileEditorService_WriteTextFileData_Call {
	_c.Call.Return(run)
	return _c
}
