// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerManagerService creates a new instance of MockServerManagerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerManagerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerManagerService {
	mock := &MockServerManagerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerManagerService is an autogenerated mock type for the ServerManagerService type
type MockServerManagerService struct {
	mock.Mock
}

type MockServerManagerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerManagerService) EXPECT() *MockServerManagerService_Expecter {
	return &MockServerManagerService_Expecter{mock: &_m.Mock}
}

// GetProcessStatus provides a mock function for the type MockServerManagerService
func (_mock *MockServerManagerService) GetProcessStatus(id int64) (*ProcessStatus, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProcessStatus")
	}

	var r0 *ProcessStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*ProcessStatus, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *ProcessStatus); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ProcessStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerManagerService_GetProcessStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProcessStatus'
type MockServerManagerService_GetProcessStatus_Call struct {
	*mock.Call
}

// GetProcessStatus is a helper method to define mock.On call
//   - id int64
func (_e *MockServerManagerService_Expecter) GetProcessStatus(id interface{}) *MockServerManagerService_GetProcessStatus_Call {
	return &MockServerManagerService_GetProcessStatus_Call{Call: _e.mock.On("GetProcessStatus", id)}
}

func (_c *MockServerManagerService_GetProcessStatus_Call) Run(run func(id int64)) *MockServerManagerService_GetProcessStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerManagerService_GetProcessStatus_Call) Return(processStatus *ProcessStatus, err error) *MockServerManagerService_GetProcessStatus_Call {
	_c.Call.Return(processStatus, err)
	return _c
}

func (_c *MockServerManagerService_GetProcessStatus_Call) RunAndReturn(run func(id int64) (*ProcessStatus, error)) *MockServerManagerService_GetProcessStatus_Call {
	_c.Call.Return(run)
	return _c
}

// StartProcess provides a mock function for the type MockServerManagerService
func (_mock *MockServerManagerService) StartProcess(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for StartProcess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerManagerService_StartProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartProcess'
type MockServerManagerService_StartProcess_Call struct {
	*mock.Call
}

// StartProcess is a helper method to define mock.On call
//   - id int64
func (_e *MockServerManagerService_Expecter) StartProcess(id interface{}) *MockServerManagerService_StartProcess_Call {
	return &MockServerManagerService_StartProcess_Call{Call: _e.mock.On("StartProcess", id)}
}

func (_c *MockServerManagerService_StartProcess_Call) Run(run func(id int64)) *MockServerManagerService_StartProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerManagerService_StartProcess_Call) Return(err error) *MockServerManagerService_StartProcess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerManagerService_StartProcess_Call) RunAndReturn(run func(id int64) error) *MockServerManagerService_StartProcess_Call {
	_c.Call.Return(run)
	return _c
}

// StartServerSequence provides a mock function for the type MockServerManagerService
func (_mock *MockServerManagerService) StartServerSequence() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartServerSequence")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerManagerService_StartServerSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartServerSequence'
type MockServerManagerService_StartServerSequence_Call struct {
	*mock.Call
}

// StartServerSequence is a helper method to define mock.On call
func (_e *MockServerManagerService_Expecter) StartServerSequence() *MockServerManagerService_StartServerSequence_Call {
	return &MockServerManagerService_StartServerSequence_Call{Call: _e.mock.On("StartServerSequence")}
}

func (_c *MockServerManagerService_StartServerSequence_Call) Run(run func()) *MockServerManagerService_StartServerSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerManagerService_StartServerSequence_Call) Return(err error) *MockServerManagerService_StartServerSequence_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerManagerService_StartServerSequence_Call) RunAndReturn(run func() error) *MockServerManagerService_StartServerSequence_Call {
	_c.Call.Return(run)
	return _c
}

// StopProcess provides a mock function for the type MockServerManagerService
func (_mock *MockServerManagerService) StopProcess(id int64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for StopProcess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerManagerService_StopProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopProcess'
type MockServerManagerService_StopProcess_Call struct {
	*mock.Call
}

// StopProcess is a helper method to define mock.On call
//   - id int64
func (_e *MockServerManagerService_Expecter) StopProcess(id interface{}) *MockServerManagerService_StopProcess_Call {
	return &MockServerManagerService_StopProcess_Call{Call: _e.mock.On("StopProcess", id)}
}

func (_c *MockServerManagerService_StopProcess_Call) Run(run func(id int64)) *MockServerManagerService_StopProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerManagerService_StopProcess_Call) Return(err error) *MockServerManagerService_StopProcess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerManagerService_StopProcess_Call) RunAndReturn(run func(id int64) error) *MockServerManagerService_StopProcess_Call {
	_c.Call.Return(run)
	return _c
}

// StopServerSequence provides a mock function for the type MockServerManagerService
func (_mock *MockServerManagerService) StopServerSequence() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopServerSequence")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerManagerService_StopServerSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopServerSequence'
type MockServerManagerService_StopServerSequence_Call struct {
	*mock.Call
}

// StopServerSequence is a helper method to define mock.On call
func (_e *MockServerManagerService_Expecter) StopServerSequence() *MockServerManagerService_StopServerSequence_Call {
	return &MockServerManagerService_StopServerSequence_Call{Call: _e.mock.On("StopServerSequence")}
}

func (_c *MockServerManagerService_StopServerSequence_Call) Run(run func()) *MockServerManagerService_StopServerSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerManagerService_StopServerSequence_Call) Return(err error) *MockServerManagerService_StopServerSequence_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerManagerService_StopServerSequence_Call) RunAndReturn(run func() error) *MockServerManagerService_StopServerSequence_Call {
	_c.Call.Return(run)
	return _c
}
