// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileEditorService creates a new instance of MockFileEditorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileEditorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileEditorService {
	mock := &MockFileEditorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileEditorService is an autogenerated mock type for the FileEditorService type
type MockFileEditorService struct {
	mock.Mock
}

type MockFileEditorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileEditorService) EXPECT() *MockFileEditorService_Expecter {
	return &MockFileEditorService_Expecter{mock: &_m.Mock}
}

// GetFileAPIEndpoint provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) GetFileAPIEndpoint(path string, fileInfo fs.FileInfo) string {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetFileAPIEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) string); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFileEditorService_GetFileAPIEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileAPIEndpoint'
type MockFileEditorService_GetFileAPIEndpoint_Call struct {
	*mock.Call
}

// GetFileAPIEndpoint is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) GetFileAPIEndpoint(path interface{}, fileInfo interface{}) *MockFileEditorService_GetFileAPIEndpoint_Call {
	return &MockFileEditorService_GetFileAPIEndpoint_Call{Call: _e.mock.On("GetFileAPIEndpoint", path, fileInfo)}
}

func (_c *MockFileEditorService_GetFileAPIEndpoint_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_GetFileAPIEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_GetFileAPIEndpoint_Call) Return(s string) *MockFileEditorService_GetFileAPIEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFileEditorService_GetFileAPIEndpoint_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) string) *MockFileEditorService_GetFileAPIEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileType provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) GetFileType(path string, fileInfo fs.FileInfo) FileType {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetFileType")
	}

	var r0 FileType
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) FileType); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(FileType)
	}
	return r0
}

// MockFileEditorService_GetFileType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileType'
type MockFileEditorService_GetFileType_Call struct {
	*mock.Call
}

// GetFileType is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) GetFileType(path interface{}, fileInfo interface{}) *MockFileEditorService_GetFileType_Call {
	return &MockFileEditorService_GetFileType_Call{Call: _e.mock.On("GetFileType", path, fileInfo)}
}

func (_c *MockFileEditorService_GetFileType_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_GetFileType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_GetFileType_Call) Return(fileType FileType) *MockFileEditorService_GetFileType_Call {
	_c.Call.Return(fileType)
	return _c
}

func (_c *MockFileEditorService_GetFileType_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) FileType) *MockFileEditorService_GetFileType_Call {
	_c.Call.Return(run)
	return _c
}

// IsFileEditable provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsFileEditable(path string, fileInfo fs.FileInfo) bool {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for IsFileEditable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) bool); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsFileEditable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFileEditable'
type MockFileEditorService_IsFileEditable_Call struct {
	*mock.Call
}

// IsFileEditable is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) IsFileEditable(path interface{}, fileInfo interface{}) *MockFileEditorService_IsFileEditable_Call {
	return &MockFileEditorService_IsFileEditable_Call{Call: _e.mock.On("IsFileEditable", path, fileInfo)}
}

func (_c *MockFileEditorService_IsFileEditable_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_IsFileEditable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsFileEditable_Call) Return(b bool) *MockFileEditorService_IsFileEditable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsFileEditable_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) bool) *MockFileEditorService_IsFileEditable_Call {
	_c.Call.Return(run)
	return _c
}

// IsFileViewable provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) IsFileViewable(path string, fileInfo fs.FileInfo) bool {
	ret := _mock.Called(path, fileInfo)

	if len(ret) == 0 {
		panic("no return value specified for IsFileViewable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, fs.FileInfo) bool); ok {
		r0 = returnFunc(path, fileInfo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileEditorService_IsFileViewable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFileViewable'
type MockFileEditorService_IsFileViewable_Call struct {
	*mock.Call
}

// IsFileViewable is a helper method to define mock.On call
//   - path string
//   - fileInfo fs.FileInfo
func (_e *MockFileEditorService_Expecter) IsFileViewable(path interface{}, fileInfo interface{}) *MockFileEditorService_IsFileViewable_Call {
	return &MockFileEditorService_IsFileViewable_Call{Call: _e.mock.On("IsFileViewable", path, fileInfo)}
}

func (_c *MockFileEditorService_IsFileViewable_Call) Run(run func(path string, fileInfo fs.FileInfo)) *MockFileEditorService_IsFileViewable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FileInfo
		if args[1] != nil {
			arg1 = args[1].(fs.FileInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_IsFileViewable_Call) Return(b bool) *MockFileEditorService_IsFileViewable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileEditorService_IsFileViewable_Call) RunAndReturn(run func(path string, fileInfo fs.FileInfo) bool) *MockFileEditorService_IsFileViewable_Call {
	_c.Call.Return(run)
	return _c
}

// ReadNPCFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) ReadNPCFileData(path string) (*NPCFileData, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadNPCFileData")
	}

	var r0 *NPCFileData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*NPCFileData, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *NPCFileData); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*NPCFileData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileEditorService_ReadNPCFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadNPCFileData'
type MockFileEditorService_ReadNPCFileData_Call struct {
	*mock.Call
}

// ReadNPCFileData is a helper method to define mock.On call
//   - path string
func (_e *MockFileEditorService_Expecter) ReadNPCFileData(path interface{}) *MockFileEditorService_ReadNPCFileData_Call {
	return &MockFileEditorService_ReadNPCFileData_Call{Call: _e.mock.On("ReadNPCFileData", path)}
}

func (_c *MockFileEditorService_ReadNPCFileData_Call) Run(run func(path string)) *MockFileEditorService_ReadNPCFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileEditorService_ReadNPCFileData_Call) Return(nPCFileData *NPCFileData, err error) *MockFileEditorService_ReadNPCFileData_Call {
	_c.Call.Return(nPCFileData, err)
	return _c
}

func (_c *MockFileEditorService_ReadNPCFileData_Call) RunAndReturn(run func(path string) (*NPCFileData, error)) *MockFileEditorService_ReadNPCFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteNPCFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteNPCFileData(path string, data *NPCFileData) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteNPCFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *NPCFileData) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteNPCFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteNPCFileData'
type MockFileEditorService_WriteNPCFileData_Call struct {
	*mock.Call
}

// WriteNPCFileData is a helper method to define mock.On call
//   - path string
//   - data *NPCFileData
func (_e *MockFileEditorService_Expecter) WriteNPCFileData(path interface{}, data interface{}) *MockFileEditorService_WriteNPCFileData_Call {
	return &MockFileEditorService_WriteNPCFileData_Call{Call: _e.mock.On("WriteNPCFileData", path, data)}
}

func (_c *MockFileEditorService_WriteNPCFileData_Call) Run(run func(path string, data *NPCFileData)) *MockFileEditorService_WriteNPCFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *NPCFileData
		if args[1] != nil {
			arg1 = args[1].(*NPCFileData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteNPCFileData_Call) Return(err error) *MockFileEditorService_WriteNPCFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteNPCFileData_Call) RunAndReturn(run func(path string, data *NPCFileData) error) *MockFileEditorService_WriteNPCFileData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteTextFileData provides a mock function for the type MockFileEditorService
func (_mock *MockFileEditorService) WriteTextFileData(path string, content string) error {
	ret := _mock.Called(path, content)

	if len(ret) == 0 {
		panic("no return value specified for WriteTextFileData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(path, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileEditorService_WriteTextFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTextFileData'
type MockFileEditorService_WriteTextFileData_Call struct {
	*mock.Call
}

// WriteTextFileData is a helper method to define mock.On call
//   - path string
//   - content string
func (_e *MockFileEditorService_Expecter) WriteTextFileData(path interface{}, content interface{}) *MockFileEditorService_WriteTextFileData_Call {
	return &MockFileEditorService_WriteTextFileData_Call{Call: _e.mock.On("WriteTextFileData", path, content)}
}

func (_c *MockFileEditorService_WriteTextFileData_Call) Run(run func(path string, content string)) *MockFileEditorService_WriteTextFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileEditorService_WriteTextFileData_Call) Return(err error) *MockFileEditorService_WriteTextFileData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileEditorService_WriteTextFileData_Call) RunAndReturn(run func(path string, content string) error) *MockFileEditorService_WriteTextFileData_Call {
	_c.Call.Return(run)
	return _c
}
