// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsCollectorService creates a new instance of MockMetricsCollectorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsCollectorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsCollectorService {
	mock := &MockMetricsCollectorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsCollectorService is an autogenerated mock type for the MetricsCollectorService type
type MockMetricsCollectorService struct {
	mock.Mock
}

type MockMetricsCollectorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsCollectorService) EXPECT() *MockMetricsCollectorService_Expecter {
	return &MockMetricsCollectorService_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockMetricsCollectorService
func (_mock *MockMetricsCollectorService) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsCollectorService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockMetricsCollectorService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockMetricsCollectorService_Expecter) Start() *MockMetricsCollectorService_Start_Call {
	return &MockMetricsCollectorService_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockMetricsCollectorService_Start_Call) Run(run func()) *MockMetricsCollectorService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricsCollectorService_Start_Call) Return(err error) *MockMetricsCollectorService_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsCollectorService_Start_Call) RunAndReturn(run func() error) *MockMetricsCollectorService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockMetricsCollectorService
func (_mock *MockMetricsCollectorService) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsCollectorService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockMetricsCollectorService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockMetricsCollectorService_Expecter) Stop() *MockMetricsCollectorService_Stop_Call {
	return &MockMetricsCollectorService_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockMetricsCollectorService_Stop_Call) Run(run func()) *MockMetricsCollectorService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricsCollectorService_Stop_Call) Return(err error) *MockMetricsCollectorService_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsCollectorService_Stop_Call) RunAndReturn(run func() error) *MockMetricsCollectorService_Stop_Call {
	_c.Call.Return(run)
	return _c
}
