// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/omnihance/omnihance-a3-agent/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerViewService creates a new instance of MockServerViewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerViewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerViewService {
	mock := &MockServerViewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerViewService is an autogenerated mock type for the ServerViewService type
type MockServerViewService struct {
	mock.Mock
}

type MockServerViewService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerViewService) EXPECT() *MockServerViewService_Expecter {
	return &MockServerViewService_Expecter{mock: &_m.Mock}
}

// GetMainMaps provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) GetMainMaps(ctx context.Context, query string) ([]ServerViewMapRow, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetMainMaps")
	}

	var r0 []ServerViewMapRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ServerViewMapRow, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ServerViewMapRow); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ServerViewMapRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_GetMainMaps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMainMaps'
type MockServerViewService_GetMainMaps_Call struct {
	*mock.Call
}

// GetMainMaps is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockServerViewService_Expecter) GetMainMaps(ctx interface{}, query interface{}) *MockServerViewService_GetMainMaps_Call {
	return &MockServerViewService_GetMainMaps_Call{Call: _e.mock.On("GetMainMaps", ctx, query)}
}

func (_c *MockServerViewService_GetMainMaps_Call) Run(run func(ctx context.Context, query string)) *MockServerViewService_GetMainMaps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerViewService_GetMainMaps_Call) Return(serverViewMapRows []ServerViewMapRow, err error) *MockServerViewService_GetMainMaps_Call {
	_c.Call.Return(serverViewMapRows, err)
	return _c
}

func (_c *MockServerViewService_GetMainMaps_Call) RunAndReturn(run func(ctx context.Context, query string) ([]ServerViewMapRow, error)) *MockServerViewService_GetMainMaps_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverview provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) GetOverview(ctx context.Context) (*ServerViewOverview, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOverview")
	}

	var r0 *ServerViewOverview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ServerViewOverview, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ServerViewOverview); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ServerViewOverview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_GetOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverview'
type MockServerViewService_GetOverview_Call struct {
	*mock.Call
}

// GetOverview is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerViewService_Expecter) GetOverview(ctx interface{}) *MockServerViewService_GetOverview_Call {
	return &MockServerViewService_GetOverview_Call{Call: _e.mock.On("GetOverview", ctx)}
}

func (_c *MockServerViewService_GetOverview_Call) Run(run func(ctx context.Context)) *MockServerViewService_GetOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerViewService_GetOverview_Call) Return(serverViewOverview *ServerViewOverview, err error) *MockServerViewService_GetOverview_Call {
	_c.Call.Return(serverViewOverview, err)
	return _c
}

func (_c *MockServerViewService_GetOverview_Call) RunAndReturn(run func(ctx context.Context) (*ServerViewOverview, error)) *MockServerViewService_GetOverview_Call {
	_c.Call.Return(run)
	return _c
}

// GetSyncStatus provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) GetSyncStatus(ctx context.Context) (*ServerViewSyncStatus, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncStatus")
	}

	var r0 *ServerViewSyncStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*ServerViewSyncStatus, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *ServerViewSyncStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ServerViewSyncStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_GetSyncStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSyncStatus'
type MockServerViewService_GetSyncStatus_Call struct {
	*mock.Call
}

// GetSyncStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerViewService_Expecter) GetSyncStatus(ctx interface{}) *MockServerViewService_GetSyncStatus_Call {
	return &MockServerViewService_GetSyncStatus_Call{Call: _e.mock.On("GetSyncStatus", ctx)}
}

func (_c *MockServerViewService_GetSyncStatus_Call) Run(run func(ctx context.Context)) *MockServerViewService_GetSyncStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerViewService_GetSyncStatus_Call) Return(serverViewSyncStatus *ServerViewSyncStatus, err error) *MockServerViewService_GetSyncStatus_Call {
	_c.Call.Return(serverViewSyncStatus, err)
	return _c
}

func (_c *MockServerViewService_GetSyncStatus_Call) RunAndReturn(run func(ctx context.Context) (*ServerViewSyncStatus, error)) *MockServerViewService_GetSyncStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetZoneDropDetails provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) GetZoneDropDetails(ctx context.Context, npcID int64, query string) ([]ServerViewDropDetailRow, error) {
	ret := _mock.Called(ctx, npcID, query)

	if len(ret) == 0 {
		panic("no return value specified for GetZoneDropDetails")
	}

	var r0 []ServerViewDropDetailRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]ServerViewDropDetailRow, error)); ok {
		return returnFunc(ctx, npcID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []ServerViewDropDetailRow); ok {
		r0 = returnFunc(ctx, npcID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ServerViewDropDetailRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, npcID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_GetZoneDropDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZoneDropDetails'
type MockServerViewService_GetZoneDropDetails_Call struct {
	*mock.Call
}

// GetZoneDropDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - npcID int64
//   - query string
func (_e *MockServerViewService_Expecter) GetZoneDropDetails(ctx interface{}, npcID interface{}, query interface{}) *MockServerViewService_GetZoneDropDetails_Call {
	return &MockServerViewService_GetZoneDropDetails_Call{Call: _e.mock.On("GetZoneDropDetails", ctx, npcID, query)}
}

func (_c *MockServerViewService_GetZoneDropDetails_Call) Run(run func(ctx context.Context, npcID int64, query string)) *MockServerViewService_GetZoneDropDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerViewService_GetZoneDropDetails_Call) Return(serverViewDropDetailRows []ServerViewDropDetailRow, err error) *MockServerViewService_GetZoneDropDetails_Call {
	_c.Call.Return(serverViewDropDetailRows, err)
	return _c
}

func (_c *MockServerViewService_GetZoneDropDetails_Call) RunAndReturn(run func(ctx context.Context, npcID int64, query string) ([]ServerViewDropDetailRow, error)) *MockServerViewService_GetZoneDropDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetZoneDrops provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) GetZoneDrops(ctx context.Context, query string) ([]ServerViewDropSummaryRow, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetZoneDrops")
	}

	var r0 []ServerViewDropSummaryRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ServerViewDropSummaryRow, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ServerViewDropSummaryRow); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ServerViewDropSummaryRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_GetZoneDrops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZoneDrops'
type MockServerViewService_GetZoneDrops_Call struct {
	*mock.Call
}

// GetZoneDrops is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockServerViewService_Expecter) GetZoneDrops(ctx interface{}, query interface{}) *MockServerViewService_GetZoneDrops_Call {
	return &MockServerViewService_GetZoneDrops_Call{Call: _e.mock.On("GetZoneDrops", ctx, query)}
}

func (_c *MockServerViewService_GetZoneDrops_Call) Run(run func(ctx context.Context, query string)) *MockServerViewService_GetZoneDrops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerViewService_GetZoneDrops_Call) Return(serverViewDropSummaryRows []ServerViewDropSummaryRow, err error) *MockServerViewService_GetZoneDrops_Call {
	_c.Call.Return(serverViewDropSummaryRows, err)
	return _c
}

func (_c *MockServerViewService_GetZoneDrops_Call) RunAndReturn(run func(ctx context.Context, query string) ([]ServerViewDropSummaryRow, error)) *MockServerViewService_GetZoneDrops_Call {
	_c.Call.Return(run)
	return _c
}

// GetZoneMaps provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) GetZoneMaps(ctx context.Context, query string) ([]ServerViewMapRow, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetZoneMaps")
	}

	var r0 []ServerViewMapRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ServerViewMapRow, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ServerViewMapRow); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ServerViewMapRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_GetZoneMaps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZoneMaps'
type MockServerViewService_GetZoneMaps_Call struct {
	*mock.Call
}

// GetZoneMaps is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockServerViewService_Expecter) GetZoneMaps(ctx interface{}, query interface{}) *MockServerViewService_GetZoneMaps_Call {
	return &MockServerViewService_GetZoneMaps_Call{Call: _e.mock.On("GetZoneMaps", ctx, query)}
}

func (_c *MockServerViewService_GetZoneMaps_Call) Run(run func(ctx context.Context, query string)) *MockServerViewService_GetZoneMaps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerViewService_GetZoneMaps_Call) Return(serverViewMapRows []ServerViewMapRow, err error) *MockServerViewService_GetZoneMaps_Call {
	_c.Call.Return(serverViewMapRows, err)
	return _c
}

func (_c *MockServerViewService_GetZoneMaps_Call) RunAndReturn(run func(ctx context.Context, query string) ([]ServerViewMapRow, error)) *MockServerViewService_GetZoneMaps_Call {
	_c.Call.Return(run)
	return _c
}

// GetZoneShopDetails provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) GetZoneShopDetails(ctx context.Context, npcID int64, query string) ([]ServerViewShopDetailRow, error) {
	ret := _mock.Called(ctx, npcID, query)

	if len(ret) == 0 {
		panic("no return value specified for GetZoneShopDetails")
	}

	var r0 []ServerViewShopDetailRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]ServerViewShopDetailRow, error)); ok {
		return returnFunc(ctx, npcID, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []ServerViewShopDetailRow); ok {
		r0 = returnFunc(ctx, npcID, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ServerViewShopDetailRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, npcID, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_GetZoneShopDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZoneShopDetails'
type MockServerViewService_GetZoneShopDetails_Call struct {
	*mock.Call
}

// GetZoneShopDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - npcID int64
//   - query string
func (_e *MockServerViewService_Expecter) GetZoneShopDetails(ctx interface{}, npcID interface{}, query interface{}) *MockServerViewService_GetZoneShopDetails_Call {
	return &MockServerViewService_GetZoneShopDetails_Call{Call: _e.mock.On("GetZoneShopDetails", ctx, npcID, query)}
}

func (_c *MockServerViewService_GetZoneShopDetails_Call) Run(run func(ctx context.Context, npcID int64, query string)) *MockServerViewService_GetZoneShopDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerViewService_GetZoneShopDetails_Call) Return(serverViewShopDetailRows []ServerViewShopDetailRow, err error) *MockServerViewService_GetZoneShopDetails_Call {
	_c.Call.Return(serverViewShopDetailRows, err)
	return _c
}

func (_c *MockServerViewService_GetZoneShopDetails_Call) RunAndReturn(run func(ctx context.Context, npcID int64, query string) ([]ServerViewShopDetailRow, error)) *MockServerViewService_GetZoneShopDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetZoneShops provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) GetZoneShops(ctx context.Context, query string) ([]ServerViewShopSummaryRow, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetZoneShops")
	}

	var r0 []ServerViewShopSummaryRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]ServerViewShopSummaryRow, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []ServerViewShopSummaryRow); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ServerViewShopSummaryRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_GetZoneShops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZoneShops'
type MockServerViewService_GetZoneShops_Call struct {
	*mock.Call
}

// GetZoneShops is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockServerViewService_Expecter) GetZoneShops(ctx interface{}, query interface{}) *MockServerViewService_GetZoneShops_Call {
	return &MockServerViewService_GetZoneShops_Call{Call: _e.mock.On("GetZoneShops", ctx, query)}
}

func (_c *MockServerViewService_GetZoneShops_Call) Run(run func(ctx context.Context, query string)) *MockServerViewService_GetZoneShops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerViewService_GetZoneShops_Call) Return(serverViewShopSummaryRows []ServerViewShopSummaryRow, err error) *MockServerViewService_GetZoneShops_Call {
	_c.Call.Return(serverViewShopSummaryRows, err)
	return _c
}

func (_c *MockServerViewService_GetZoneShops_Call) RunAndReturn(run func(ctx context.Context, query string) ([]ServerViewShopSummaryRow, error)) *MockServerViewService_GetZoneShops_Call {
	_c.Call.Return(run)
	return _c
}

// GetZoneSpawns provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) GetZoneSpawns(ctx context.Context, mapQuery string, npcQuery string) ([]ServerViewSpawnSummaryRow, error) {
	ret := _mock.Called(ctx, mapQuery, npcQuery)

	if len(ret) == 0 {
		panic("no return value specified for GetZoneSpawns")
	}

	var r0 []ServerViewSpawnSummaryRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]ServerViewSpawnSummaryRow, error)); ok {
		return returnFunc(ctx, mapQuery, npcQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []ServerViewSpawnSummaryRow); ok {
		r0 = returnFunc(ctx, mapQuery, npcQuery)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ServerViewSpawnSummaryRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, mapQuery, npcQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_GetZoneSpawns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZoneSpawns'
type MockServerViewService_GetZoneSpawns_Call struct {
	*mock.Call
}

// GetZoneSpawns is a helper method to define mock.On call
//   - ctx context.Context
//   - mapQuery string
//   - npcQuery string
func (_e *MockServerViewService_Expecter) GetZoneSpawns(ctx interface{}, mapQuery interface{}, npcQuery interface{}) *MockServerViewService_GetZoneSpawns_Call {
	return &MockServerViewService_GetZoneSpawns_Call{Call: _e.mock.On("GetZoneSpawns", ctx, mapQuery, npcQuery)}
}

func (_c *MockServerViewService_GetZoneSpawns_Call) Run(run func(ctx context.Context, mapQuery string, npcQuery string)) *MockServerViewService_GetZoneSpawns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerViewService_GetZoneSpawns_Call) Return(serverViewSpawnSummaryRows []ServerViewSpawnSummaryRow, err error) *MockServerViewService_GetZoneSpawns_Call {
	_c.Call.Return(serverViewSpawnSummaryRows, err)
	return _c
}

func (_c *MockServerViewService_GetZoneSpawns_Call) RunAndReturn(run func(ctx context.Context, mapQuery string, npcQuery string) ([]ServerViewSpawnSummaryRow, error)) *MockServerViewService_GetZoneSpawns_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerViewService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockServerViewService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockServerViewService_Expecter) Start() *MockServerViewService_Start_Call {
	return &MockServerViewService_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockServerViewService_Start_Call) Run(run func()) *MockServerViewService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerViewService_Start_Call) Return(err error) *MockServerViewService_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerViewService_Start_Call) RunAndReturn(run func() error) *MockServerViewService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StartSync provides a mock function for the type MockServerViewService
func (_mock *MockServerViewService) StartSync(ctx context.Context, userID *int64) (*db.ServerViewSyncRun, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for StartSync")
	}

	var r0 *db.ServerViewSyncRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64) (*db.ServerViewSyncRun, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64) *db.ServerViewSyncRun); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.ServerViewSyncRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerViewService_StartSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSync'
type MockServerViewService_StartSync_Call struct {
	*mock.Call
}

// StartSync is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *int64
func (_e *MockServerViewService_Expecter) StartSync(ctx interface{}, userID interface{}) *MockServerViewService_StartSync_Call {
	return &MockServerViewService_StartSync_Call{Call: _e.mock.On("StartSync", ctx, userID)}
}

func (_c *MockServerViewService_StartSync_Call) Run(run func(ctx context.Context, userID *int64)) *MockServerViewService_StartSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerViewService_StartSync_Call) Return(serverViewSyncRun *db.ServerViewSyncRun, err error) *MockServerViewService_StartSync_Call {
	_c.Call.Return(serverViewSyncRun, err)
	return _c
}

func (_c *MockServerViewService_StartSync_Call) RunAndReturn(run func(ctx context.Context, userID *int64) (*db.ServerViewSyncRun, error)) *MockServerViewService_StartSync_Call {
	_c.Call.Return(run)
	return _c
}
