// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"time"

	"github.com/doug-martin/goqu/v9"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInternalDB creates a new instance of MockInternalDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInternalDB {
	mock := &MockInternalDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInternalDB is an autogenerated mock type for the InternalDB type
type MockInternalDB struct {
	mock.Mock
}

type MockInternalDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalDB) EXPECT() *MockInternalDB_Expecter {
	return &MockInternalDB_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) BeginTx() (*goqu.TxDatabase, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *goqu.TxDatabase
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*goqu.TxDatabase, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *goqu.TxDatabase); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*goqu.TxDatabase)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockInternalDB_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) BeginTx() *MockInternalDB_BeginTx_Call {
	return &MockInternalDB_BeginTx_Call{Call: _e.mock.On("BeginTx")}
}

func (_c *MockInternalDB_BeginTx_Call) Run(run func()) *MockInternalDB_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_BeginTx_Call) Return(txDatabase *goqu.TxDatabase, err error) *MockInternalDB_BeginTx_Call {
	_c.Call.Return(txDatabase, err)
	return _c
}

func (_c *MockInternalDB_BeginTx_Call) RunAndReturn(run func() (*goqu.TxDatabase, error)) *MockInternalDB_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockInternalDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) Close() *MockInternalDB_Close_Call {
	return &MockInternalDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockInternalDB_Close_Call) Run(run func()) *MockInternalDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_Close_Call) Return(err error) *MockInternalDB_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_Close_Call) RunAndReturn(run func() error) *MockInternalDB_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) Connect() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockInternalDB_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) Connect() *MockInternalDB_Connect_Call {
	return &MockInternalDB_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MockInternalDB_Connect_Call) Run(run func()) *MockInternalDB_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_Connect_Call) Return(err error) *MockInternalDB_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_Connect_Call) RunAndReturn(run func() error) *MockInternalDB_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFileRevision provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) CreateFileRevision(tx *goqu.TxDatabase, fileID string, originalPath string, revisionPath string, previousHash string, currentHash string, createdBy int64) (int64, error) {
	ret := _mock.Called(tx, fileID, originalPath, revisionPath, previousHash, currentHash, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateFileRevision")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*goqu.TxDatabase, string, string, string, string, string, int64) (int64, error)); ok {
		return returnFunc(tx, fileID, originalPath, revisionPath, previousHash, currentHash, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(*goqu.TxDatabase, string, string, string, string, string, int64) int64); ok {
		r0 = returnFunc(tx, fileID, originalPath, revisionPath, previousHash, currentHash, createdBy)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*goqu.TxDatabase, string, string, string, string, string, int64) error); ok {
		r1 = returnFunc(tx, fileID, originalPath, revisionPath, previousHash, currentHash, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_CreateFileRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFileRevision'
type MockInternalDB_CreateFileRevision_Call struct {
	*mock.Call
}

// CreateFileRevision is a helper method to define mock.On call
//   - tx *goqu.TxDatabase
//   - fileID string
//   - originalPath string
//   - revisionPath string
//   - previousHash string
//   - currentHash string
//   - createdBy int64
func (_e *MockInternalDB_Expecter) CreateFileRevision(tx interface{}, fileID interface{}, originalPath interface{}, revisionPath interface{}, previousHash interface{}, currentHash interface{}, createdBy interface{}) *MockInternalDB_CreateFileRevision_Call {
	return &MockInternalDB_CreateFileRevision_Call{Call: _e.mock.On("CreateFileRevision", tx, fileID, originalPath, revisionPath, previousHash, currentHash, createdBy)}
}

func (_c *MockInternalDB_CreateFileRevision_Call) Run(run func(tx *goqu.TxDatabase, fileID string, originalPath string, revisionPath string, previousHash string, currentHash string, createdBy int64)) *MockInternalDB_CreateFileRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *goqu.TxDatabase
		if args[0] != nil {
			arg0 = args[0].(*goqu.TxDatabase)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 int64
		if args[6] != nil {
			arg6 = args[6].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockInternalDB_CreateFileRevision_Call) Return(n int64, err error) *MockInternalDB_CreateFileRevision_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockInternalDB_CreateFileRevision_Call) RunAndReturn(run func(tx *goqu.TxDatabase, fileID string, originalPath string, revisionPath string, previousHash string, currentHash string, createdBy int64) (int64, error)) *MockInternalDB_CreateFileRevision_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) CreateSession(userID int64, expiresAt time.Time, userAgent *string, ipAddress *string) (*Session, error) {
	ret := _mock.Called(userID, expiresAt, userAgent, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, time.Time, *string, *string) (*Session, error)); ok {
		return returnFunc(userID, expiresAt, userAgent, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, time.Time, *string, *string) *Session); ok {
		r0 = returnFunc(userID, expiresAt, userAgent, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, time.Time, *string, *string) error); ok {
		r1 = returnFunc(userID, expiresAt, userAgent, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockInternalDB_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - userID int64
//   - expiresAt time.Time
//   - userAgent *string
//   - ipAddress *string
func (_e *MockInternalDB_Expecter) CreateSession(userID interface{}, expiresAt interface{}, userAgent interface{}, ipAddress interface{}) *MockInternalDB_CreateSession_Call {
	return &MockInternalDB_CreateSession_Call{Call: _e.mock.On("CreateSession", userID, expiresAt, userAgent, ipAddress)}
}

func (_c *MockInternalDB_CreateSession_Call) Run(run func(userID int64, expiresAt time.Time, userAgent *string, ipAddress *string)) *MockInternalDB_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInternalDB_CreateSession_Call) Return(session *Session, err error) *MockInternalDB_CreateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockInternalDB_CreateSession_Call) RunAndReturn(run func(userID int64, expiresAt time.Time, userAgent *string, ipAddress *string) (*Session, error)) *MockInternalDB_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) CreateUser(email string, password string, roles string, createdBy *int64) (*User, error) {
	ret := _mock.Called(email, password, roles, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, *int64) (*User, error)); ok {
		return returnFunc(email, password, roles, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, *int64) *User); ok {
		r0 = returnFunc(email, password, roles, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, *int64) error); ok {
		r1 = returnFunc(email, password, roles, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockInternalDB_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - email string
//   - password string
//   - roles string
//   - createdBy *int64
func (_e *MockInternalDB_Expecter) CreateUser(email interface{}, password interface{}, roles interface{}, createdBy interface{}) *MockInternalDB_CreateUser_Call {
	return &MockInternalDB_CreateUser_Call{Call: _e.mock.On("CreateUser", email, password, roles, createdBy)}
}

func (_c *MockInternalDB_CreateUser_Call) Run(run func(email string, password string, roles string, createdBy *int64)) *MockInternalDB_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInternalDB_CreateUser_Call) Return(user *User, err error) *MockInternalDB_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockInternalDB_CreateUser_Call) RunAndReturn(run func(email string, password string, roles string, createdBy *int64) (*User, error)) *MockInternalDB_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserWithStatus provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) CreateUserWithStatus(email string, password string, roles string, status string, createdBy *int64) (*User, error) {
	ret := _mock.Called(email, password, roles, status, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithStatus")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, *int64) (*User, error)); ok {
		return returnFunc(email, password, roles, status, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, *int64) *User); ok {
		r0 = returnFunc(email, password, roles, status, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string, *int64) error); ok {
		r1 = returnFunc(email, password, roles, status, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_CreateUserWithStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserWithStatus'
type MockInternalDB_CreateUserWithStatus_Call struct {
	*mock.Call
}

// CreateUserWithStatus is a helper method to define mock.On call
//   - email string
//   - password string
//   - roles string
//   - status string
//   - createdBy *int64
func (_e *MockInternalDB_Expecter) CreateUserWithStatus(email interface{}, password interface{}, roles interface{}, status interface{}, createdBy interface{}) *MockInternalDB_CreateUserWithStatus_Call {
	return &MockInternalDB_CreateUserWithStatus_Call{Call: _e.mock.On("CreateUserWithStatus", email, password, roles, status, createdBy)}
}

func (_c *MockInternalDB_CreateUserWithStatus_Call) Run(run func(email string, password string, roles string, status string, createdBy *int64)) *MockInternalDB_CreateUserWithStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInternalDB_CreateUserWithStatus_Call) Return(user *User, err error) *MockInternalDB_CreateUserWithStatus_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockInternalDB_CreateUserWithStatus_Call) RunAndReturn(run func(email string, password string, roles string, status string, createdBy *int64) (*User, error)) *MockInternalDB_CreateUserWithStatus_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredSessions provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) DeleteExpiredSessions() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_DeleteExpiredSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredSessions'
type MockInternalDB_DeleteExpiredSessions_Call struct {
	*mock.Call
}

// DeleteExpiredSessions is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) DeleteExpiredSessions() *MockInternalDB_DeleteExpiredSessions_Call {
	return &MockInternalDB_DeleteExpiredSessions_Call{Call: _e.mock.On("DeleteExpiredSessions")}
}

func (_c *MockInternalDB_DeleteExpiredSessions_Call) Run(run func()) *MockInternalDB_DeleteExpiredSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_DeleteExpiredSessions_Call) Return(err error) *MockInternalDB_DeleteExpiredSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_DeleteExpiredSessions_Call) RunAndReturn(run func() error) *MockInternalDB_DeleteExpiredSessions_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOldMetrics provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) DeleteOldMetrics(retentionDays int) error {
	ret := _mock.Called(retentionDays)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldMetrics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(retentionDays)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_DeleteOldMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOldMetrics'
type MockInternalDB_DeleteOldMetrics_Call struct {
	*mock.Call
}

// DeleteOldMetrics is a helper method to define mock.On call
//   - retentionDays int
func (_e *MockInternalDB_Expecter) DeleteOldMetrics(retentionDays interface{}) *MockInternalDB_DeleteOldMetrics_Call {
	return &MockInternalDB_DeleteOldMetrics_Call{Call: _e.mock.On("DeleteOldMetrics", retentionDays)}
}

func (_c *MockInternalDB_DeleteOldMetrics_Call) Run(run func(retentionDays int)) *MockInternalDB_DeleteOldMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_DeleteOldMetrics_Call) Return(err error) *MockInternalDB_DeleteOldMetrics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_DeleteOldMetrics_Call) RunAndReturn(run func(retentionDays int) error) *MockInternalDB_DeleteOldMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) DeleteSession(sessionID string) error {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockInternalDB_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - sessionID string
func (_e *MockInternalDB_Expecter) DeleteSession(sessionID interface{}) *MockInternalDB_DeleteSession_Call {
	return &MockInternalDB_DeleteSession_Call{Call: _e.mock.On("DeleteSession", sessionID)}
}

func (_c *MockInternalDB_DeleteSession_Call) Run(run func(sessionID string)) *MockInternalDB_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_DeleteSession_Call) Return(err error) *MockInternalDB_DeleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_DeleteSession_Call) RunAndReturn(run func(sessionID string) error) *MockInternalDB_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSetting provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) DeleteSetting(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_DeleteSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSetting'
type MockInternalDB_DeleteSetting_Call struct {
	*mock.Call
}

// DeleteSetting is a helper method to define mock.On call
//   - key string
func (_e *MockInternalDB_Expecter) DeleteSetting(key interface{}) *MockInternalDB_DeleteSetting_Call {
	return &MockInternalDB_DeleteSetting_Call{Call: _e.mock.On("DeleteSetting", key)}
}

func (_c *MockInternalDB_DeleteSetting_Call) Run(run func(key string)) *MockInternalDB_DeleteSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_DeleteSetting_Call) Return(err error) *MockInternalDB_DeleteSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_DeleteSetting_Call) RunAndReturn(run func(key string) error) *MockInternalDB_DeleteSetting_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) DeleteUser(userID int64, deletedBy int64) error {
	ret := _mock.Called(userID, deletedBy)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = returnFunc(userID, deletedBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockInternalDB_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - userID int64
//   - deletedBy int64
func (_e *MockInternalDB_Expecter) DeleteUser(userID interface{}, deletedBy interface{}) *MockInternalDB_DeleteUser_Call {
	return &MockInternalDB_DeleteUser_Call{Call: _e.mock.On("DeleteUser", userID, deletedBy)}
}

func (_c *MockInternalDB_DeleteUser_Call) Run(run func(userID int64, deletedBy int64)) *MockInternalDB_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInternalDB_DeleteUser_Call) Return(err error) *MockInternalDB_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_DeleteUser_Call) RunAndReturn(run func(userID int64, deletedBy int64) error) *MockInternalDB_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserSessions provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) DeleteUserSessions(userID int64) error {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_DeleteUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserSessions'
type MockInternalDB_DeleteUserSessions_Call struct {
	*mock.Call
}

// DeleteUserSessions is a helper method to define mock.On call
//   - userID int64
func (_e *MockInternalDB_Expecter) DeleteUserSessions(userID interface{}) *MockInternalDB_DeleteUserSessions_Call {
	return &MockInternalDB_DeleteUserSessions_Call{Call: _e.mock.On("DeleteUserSessions", userID)}
}

func (_c *MockInternalDB_DeleteUserSessions_Call) Run(run func(userID int64)) *MockInternalDB_DeleteUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_DeleteUserSessions_Call) Return(err error) *MockInternalDB_DeleteUserSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_DeleteUserSessions_Call) RunAndReturn(run func(userID int64) error) *MockInternalDB_DeleteUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveUserByID provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetActiveUserByID(userID int64) (*User, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveUserByID")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*User, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *User); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetActiveUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveUserByID'
type MockInternalDB_GetActiveUserByID_Call struct {
	*mock.Call
}

// GetActiveUserByID is a helper method to define mock.On call
//   - userID int64
func (_e *MockInternalDB_Expecter) GetActiveUserByID(userID interface{}) *MockInternalDB_GetActiveUserByID_Call {
	return &MockInternalDB_GetActiveUserByID_Call{Call: _e.mock.On("GetActiveUserByID", userID)}
}

func (_c *MockInternalDB_GetActiveUserByID_Call) Run(run func(userID int64)) *MockInternalDB_GetActiveUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetActiveUserByID_Call) Return(user *User, err error) *MockInternalDB_GetActiveUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockInternalDB_GetActiveUserByID_Call) RunAndReturn(run func(userID int64) (*User, error)) *MockInternalDB_GetActiveUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAdminUserCount provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetAdminUserCount() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAdminUserCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetAdminUserCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminUserCount'
type MockInternalDB_GetAdminUserCount_Call struct {
	*mock.Call
}

// GetAdminUserCount is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) GetAdminUserCount() *MockInternalDB_GetAdminUserCount_Call {
	return &MockInternalDB_GetAdminUserCount_Call{Call: _e.mock.On("GetAdminUserCount")}
}

func (_c *MockInternalDB_GetAdminUserCount_Call) Run(run func()) *MockInternalDB_GetAdminUserCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_GetAdminUserCount_Call) Return(n int64, err error) *MockInternalDB_GetAdminUserCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockInternalDB_GetAdminUserCount_Call) RunAndReturn(run func() (int64, error)) *MockInternalDB_GetAdminUserCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompletedRevisionCount provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetCompletedRevisionCount(fileID string) (int64, error) {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetCompletedRevisionCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(fileID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetCompletedRevisionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompletedRevisionCount'
type MockInternalDB_GetCompletedRevisionCount_Call struct {
	*mock.Call
}

// GetCompletedRevisionCount is a helper method to define mock.On call
//   - fileID string
func (_e *MockInternalDB_Expecter) GetCompletedRevisionCount(fileID interface{}) *MockInternalDB_GetCompletedRevisionCount_Call {
	return &MockInternalDB_GetCompletedRevisionCount_Call{Call: _e.mock.On("GetCompletedRevisionCount", fileID)}
}

func (_c *MockInternalDB_GetCompletedRevisionCount_Call) Run(run func(fileID string)) *MockInternalDB_GetCompletedRevisionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetCompletedRevisionCount_Call) Return(n int64, err error) *MockInternalDB_GetCompletedRevisionCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockInternalDB_GetCompletedRevisionCount_Call) RunAndReturn(run func(fileID string) (int64, error)) *MockInternalDB_GetCompletedRevisionCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileRevision provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetFileRevision(revisionID int64) (*FileRevision, error) {
	ret := _mock.Called(revisionID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileRevision")
	}

	var r0 *FileRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*FileRevision, error)); ok {
		return returnFunc(revisionID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *FileRevision); ok {
		r0 = returnFunc(revisionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FileRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(revisionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetFileRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileRevision'
type MockInternalDB_GetFileRevision_Call struct {
	*mock.Call
}

// GetFileRevision is a helper method to define mock.On call
//   - revisionID int64
func (_e *MockInternalDB_Expecter) GetFileRevision(revisionID interface{}) *MockInternalDB_GetFileRevision_Call {
	return &MockInternalDB_GetFileRevision_Call{Call: _e.mock.On("GetFileRevision", revisionID)}
}

func (_c *MockInternalDB_GetFileRevision_Call) Run(run func(revisionID int64)) *MockInternalDB_GetFileRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetFileRevision_Call) Return(fileRevision *FileRevision, err error) *MockInternalDB_GetFileRevision_Call {
	_c.Call.Return(fileRevision, err)
	return _c
}

func (_c *MockInternalDB_GetFileRevision_Call) RunAndReturn(run func(revisionID int64) (*FileRevision, error)) *MockInternalDB_GetFileRevision_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastCompletedFileRevision provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetLastCompletedFileRevision(fileID string) (*FileRevision, error) {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastCompletedFileRevision")
	}

	var r0 *FileRevision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*FileRevision, error)); ok {
		return returnFunc(fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *FileRevision); ok {
		r0 = returnFunc(fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FileRevision)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetLastCompletedFileRevision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastCompletedFileRevision'
type MockInternalDB_GetLastCompletedFileRevision_Call struct {
	*mock.Call
}

// GetLastCompletedFileRevision is a helper method to define mock.On call
//   - fileID string
func (_e *MockInternalDB_Expecter) GetLastCompletedFileRevision(fileID interface{}) *MockInternalDB_GetLastCompletedFileRevision_Call {
	return &MockInternalDB_GetLastCompletedFileRevision_Call{Call: _e.mock.On("GetLastCompletedFileRevision", fileID)}
}

func (_c *MockInternalDB_GetLastCompletedFileRevision_Call) Run(run func(fileID string)) *MockInternalDB_GetLastCompletedFileRevision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetLastCompletedFileRevision_Call) Return(fileRevision *FileRevision, err error) *MockInternalDB_GetLastCompletedFileRevision_Call {
	_c.Call.Return(fileRevision, err)
	return _c
}

func (_c *MockInternalDB_GetLastCompletedFileRevision_Call) RunAndReturn(run func(fileID string) (*FileRevision, error)) *MockInternalDB_GetLastCompletedFileRevision_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestSamples provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetLatestSamples() ([]LatestSample, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSamples")
	}

	var r0 []LatestSample
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]LatestSample, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []LatestSample); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]LatestSample)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetLatestSamples_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSamples'
type MockInternalDB_GetLatestSamples_Call struct {
	*mock.Call
}

// GetLatestSamples is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) GetLatestSamples() *MockInternalDB_GetLatestSamples_Call {
	return &MockInternalDB_GetLatestSamples_Call{Call: _e.mock.On("GetLatestSamples")}
}

func (_c *MockInternalDB_GetLatestSamples_Call) Run(run func()) *MockInternalDB_GetLatestSamples_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_GetLatestSamples_Call) Return(latestSamples []LatestSample, err error) *MockInternalDB_GetLatestSamples_Call {
	_c.Call.Return(latestSamples, err)
	return _c
}

func (_c *MockInternalDB_GetLatestSamples_Call) RunAndReturn(run func() ([]LatestSample, error)) *MockInternalDB_GetLatestSamples_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetricSamplesByTimeRange provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetMetricSamplesByTimeRange(metricName string, startTime int64, endTime int64) ([]MetricSampleWithLabels, error) {
	ret := _mock.Called(metricName, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetMetricSamplesByTimeRange")
	}

	var r0 []MetricSampleWithLabels
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int64, int64) ([]MetricSampleWithLabels, error)); ok {
		return returnFunc(metricName, startTime, endTime)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int64, int64) []MetricSampleWithLabels); ok {
		r0 = returnFunc(metricName, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MetricSampleWithLabels)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int64, int64) error); ok {
		r1 = returnFunc(metricName, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetMetricSamplesByTimeRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetricSamplesByTimeRange'
type MockInternalDB_GetMetricSamplesByTimeRange_Call struct {
	*mock.Call
}

// GetMetricSamplesByTimeRange is a helper method to define mock.On call
//   - metricName string
//   - startTime int64
//   - endTime int64
func (_e *MockInternalDB_Expecter) GetMetricSamplesByTimeRange(metricName interface{}, startTime interface{}, endTime interface{}) *MockInternalDB_GetMetricSamplesByTimeRange_Call {
	return &MockInternalDB_GetMetricSamplesByTimeRange_Call{Call: _e.mock.On("GetMetricSamplesByTimeRange", metricName, startTime, endTime)}
}

func (_c *MockInternalDB_GetMetricSamplesByTimeRange_Call) Run(run func(metricName string, startTime int64, endTime int64)) *MockInternalDB_GetMetricSamplesByTimeRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetMetricSamplesByTimeRange_Call) Return(metricSampleWithLabelss []MetricSampleWithLabels, err error) *MockInternalDB_GetMetricSamplesByTimeRange_Call {
	_c.Call.Return(metricSampleWithLabelss, err)
	return _c
}

func (_c *MockInternalDB_GetMetricSamplesByTimeRange_Call) RunAndReturn(run func(metricName string, startTime int64, endTime int64) ([]MetricSampleWithLabels, error)) *MockInternalDB_GetMetricSamplesByTimeRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetRevisionSummary provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetRevisionSummary(fileID string) (*RevisionSummary, error) {
	ret := _mock.Called(fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetRevisionSummary")
	}

	var r0 *RevisionSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*RevisionSummary, error)); ok {
		return returnFunc(fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *RevisionSummary); ok {
		r0 = returnFunc(fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RevisionSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetRevisionSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRevisionSummary'
type MockInternalDB_GetRevisionSummary_Call struct {
	*mock.Call
}

// GetRevisionSummary is a helper method to define mock.On call
//   - fileID string
func (_e *MockInternalDB_Expecter) GetRevisionSummary(fileID interface{}) *MockInternalDB_GetRevisionSummary_Call {
	return &MockInternalDB_GetRevisionSummary_Call{Call: _e.mock.On("GetRevisionSummary", fileID)}
}

func (_c *MockInternalDB_GetRevisionSummary_Call) Run(run func(fileID string)) *MockInternalDB_GetRevisionSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetRevisionSummary_Call) Return(revisionSummary *RevisionSummary, err error) *MockInternalDB_GetRevisionSummary_Call {
	_c.Call.Return(revisionSummary, err)
	return _c
}

func (_c *MockInternalDB_GetRevisionSummary_Call) RunAndReturn(run func(fileID string) (*RevisionSummary, error)) *MockInternalDB_GetRevisionSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeriesWithLabels provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetSeriesWithLabels() ([]SeriesWithLabels, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSeriesWithLabels")
	}

	var r0 []SeriesWithLabels
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]SeriesWithLabels, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []SeriesWithLabels); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SeriesWithLabels)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetSeriesWithLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeriesWithLabels'
type MockInternalDB_GetSeriesWithLabels_Call struct {
	*mock.Call
}

// GetSeriesWithLabels is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) GetSeriesWithLabels() *MockInternalDB_GetSeriesWithLabels_Call {
	return &MockInternalDB_GetSeriesWithLabels_Call{Call: _e.mock.On("GetSeriesWithLabels")}
}

func (_c *MockInternalDB_GetSeriesWithLabels_Call) Run(run func()) *MockInternalDB_GetSeriesWithLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_GetSeriesWithLabels_Call) Return(seriesWithLabelss []SeriesWithLabels, err error) *MockInternalDB_GetSeriesWithLabels_Call {
	_c.Call.Return(seriesWithLabelss, err)
	return _c
}

func (_c *MockInternalDB_GetSeriesWithLabels_Call) RunAndReturn(run func() ([]SeriesWithLabels, error)) *MockInternalDB_GetSeriesWithLabels_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetSession(sessionID string) (*Session, error) {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*Session, error)); ok {
		return returnFunc(sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *Session); ok {
		r0 = returnFunc(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockInternalDB_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - sessionID string
func (_e *MockInternalDB_Expecter) GetSession(sessionID interface{}) *MockInternalDB_GetSession_Call {
	return &MockInternalDB_GetSession_Call{Call: _e.mock.On("GetSession", sessionID)}
}

func (_c *MockInternalDB_GetSession_Call) Run(run func(sessionID string)) *MockInternalDB_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetSession_Call) Return(session *Session, err error) *MockInternalDB_GetSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockInternalDB_GetSession_Call) RunAndReturn(run func(sessionID string) (*Session, error)) *MockInternalDB_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetting provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetSetting(key string) (*Settings, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetSetting")
	}

	var r0 *Settings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*Settings, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *Settings); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Settings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetting'
type MockInternalDB_GetSetting_Call struct {
	*mock.Call
}

// GetSetting is a helper method to define mock.On call
//   - key string
func (_e *MockInternalDB_Expecter) GetSetting(key interface{}) *MockInternalDB_GetSetting_Call {
	return &MockInternalDB_GetSetting_Call{Call: _e.mock.On("GetSetting", key)}
}

func (_c *MockInternalDB_GetSetting_Call) Run(run func(key string)) *MockInternalDB_GetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetSetting_Call) Return(settings *Settings, err error) *MockInternalDB_GetSetting_Call {
	_c.Call.Return(settings, err)
	return _c
}

func (_c *MockInternalDB_GetSetting_Call) RunAndReturn(run func(key string) (*Settings, error)) *MockInternalDB_GetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettings provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetSettings() ([]Settings, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 []Settings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Settings, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Settings); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Settings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettings'
type MockInternalDB_GetSettings_Call struct {
	*mock.Call
}

// GetSettings is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) GetSettings() *MockInternalDB_GetSettings_Call {
	return &MockInternalDB_GetSettings_Call{Call: _e.mock.On("GetSettings")}
}

func (_c *MockInternalDB_GetSettings_Call) Run(run func()) *MockInternalDB_GetSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_GetSettings_Call) Return(settingss []Settings, err error) *MockInternalDB_GetSettings_Call {
	_c.Call.Return(settingss, err)
	return _c
}

func (_c *MockInternalDB_GetSettings_Call) RunAndReturn(run func() ([]Settings, error)) *MockInternalDB_GetSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetUserByEmail(email string) (*User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockInternalDB_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockInternalDB_Expecter) GetUserByEmail(email interface{}) *MockInternalDB_GetUserByEmail_Call {
	return &MockInternalDB_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", email)}
}

func (_c *MockInternalDB_GetUserByEmail_Call) Run(run func(email string)) *MockInternalDB_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetUserByEmail_Call) Return(user *User, err error) *MockInternalDB_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockInternalDB_GetUserByEmail_Call) RunAndReturn(run func(email string) (*User, error)) *MockInternalDB_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmailIncludeDeleted provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetUserByEmailIncludeDeleted(email string) (*User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmailIncludeDeleted")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetUserByEmailIncludeDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmailIncludeDeleted'
type MockInternalDB_GetUserByEmailIncludeDeleted_Call struct {
	*mock.Call
}

// GetUserByEmailIncludeDeleted is a helper method to define mock.On call
//   - email string
func (_e *MockInternalDB_Expecter) GetUserByEmailIncludeDeleted(email interface{}) *MockInternalDB_GetUserByEmailIncludeDeleted_Call {
	return &MockInternalDB_GetUserByEmailIncludeDeleted_Call{Call: _e.mock.On("GetUserByEmailIncludeDeleted", email)}
}

func (_c *MockInternalDB_GetUserByEmailIncludeDeleted_Call) Run(run func(email string)) *MockInternalDB_GetUserByEmailIncludeDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetUserByEmailIncludeDeleted_Call) Return(user *User, err error) *MockInternalDB_GetUserByEmailIncludeDeleted_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockInternalDB_GetUserByEmailIncludeDeleted_Call) RunAndReturn(run func(email string) (*User, error)) *MockInternalDB_GetUserByEmailIncludeDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetUserByID(userID int64) (*User, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*User, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *User); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockInternalDB_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - userID int64
func (_e *MockInternalDB_Expecter) GetUserByID(userID interface{}) *MockInternalDB_GetUserByID_Call {
	return &MockInternalDB_GetUserByID_Call{Call: _e.mock.On("GetUserByID", userID)}
}

func (_c *MockInternalDB_GetUserByID_Call) Run(run func(userID int64)) *MockInternalDB_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetUserByID_Call) Return(user *User, err error) *MockInternalDB_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockInternalDB_GetUserByID_Call) RunAndReturn(run func(userID int64) (*User, error)) *MockInternalDB_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByIDIncludeDeleted provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetUserByIDIncludeDeleted(userID int64) (*User, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByIDIncludeDeleted")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64) (*User, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) *User); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetUserByIDIncludeDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByIDIncludeDeleted'
type MockInternalDB_GetUserByIDIncludeDeleted_Call struct {
	*mock.Call
}

// GetUserByIDIncludeDeleted is a helper method to define mock.On call
//   - userID int64
func (_e *MockInternalDB_Expecter) GetUserByIDIncludeDeleted(userID interface{}) *MockInternalDB_GetUserByIDIncludeDeleted_Call {
	return &MockInternalDB_GetUserByIDIncludeDeleted_Call{Call: _e.mock.On("GetUserByIDIncludeDeleted", userID)}
}

func (_c *MockInternalDB_GetUserByIDIncludeDeleted_Call) Run(run func(userID int64)) *MockInternalDB_GetUserByIDIncludeDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_GetUserByIDIncludeDeleted_Call) Return(user *User, err error) *MockInternalDB_GetUserByIDIncludeDeleted_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockInternalDB_GetUserByIDIncludeDeleted_Call) RunAndReturn(run func(userID int64) (*User, error)) *MockInternalDB_GetUserByIDIncludeDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) GetUsers() ([]User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalDB_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockInternalDB_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) GetUsers() *MockInternalDB_GetUsers_Call {
	return &MockInternalDB_GetUsers_Call{Call: _e.mock.On("GetUsers")}
}

func (_c *MockInternalDB_GetUsers_Call) Run(run func()) *MockInternalDB_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_GetUsers_Call) Return(users []User, err error) *MockInternalDB_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockInternalDB_GetUsers_Call) RunAndReturn(run func() ([]User, error)) *MockInternalDB_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMetric provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) InsertMetric(metricName string, metricType MetricType, labels map[string]string, value float64, timestamp *int64, unit *string, description *string) error {
	ret := _mock.Called(metricName, metricType, labels, value, timestamp, unit, description)

	if len(ret) == 0 {
		panic("no return value specified for InsertMetric")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, MetricType, map[string]string, float64, *int64, *string, *string) error); ok {
		r0 = returnFunc(metricName, metricType, labels, value, timestamp, unit, description)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_InsertMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMetric'
type MockInternalDB_InsertMetric_Call struct {
	*mock.Call
}

// InsertMetric is a helper method to define mock.On call
//   - metricName string
//   - metricType MetricType
//   - labels map[string]string
//   - value float64
//   - timestamp *int64
//   - unit *string
//   - description *string
func (_e *MockInternalDB_Expecter) InsertMetric(metricName interface{}, metricType interface{}, labels interface{}, value interface{}, timestamp interface{}, unit interface{}, description interface{}) *MockInternalDB_InsertMetric_Call {
	return &MockInternalDB_InsertMetric_Call{Call: _e.mock.On("InsertMetric", metricName, metricType, labels, value, timestamp, unit, description)}
}

func (_c *MockInternalDB_InsertMetric_Call) Run(run func(metricName string, metricType MetricType, labels map[string]string, value float64, timestamp *int64, unit *string, description *string)) *MockInternalDB_InsertMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 MetricType
		if args[1] != nil {
			arg1 = args[1].(MetricType)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		var arg6 *string
		if args[6] != nil {
			arg6 = args[6].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockInternalDB_InsertMetric_Call) Return(err error) *MockInternalDB_InsertMetric_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_InsertMetric_Call) RunAndReturn(run func(metricName string, metricType MetricType, labels map[string]string, value float64, timestamp *int64, unit *string, description *string) error) *MockInternalDB_InsertMetric_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMetricSample provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) InsertMetricSample(seriesID int64, value float64, timestamp *int64) error {
	ret := _mock.Called(seriesID, value, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for InsertMetricSample")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, float64, *int64) error); ok {
		r0 = returnFunc(seriesID, value, timestamp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_InsertMetricSample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMetricSample'
type MockInternalDB_InsertMetricSample_Call struct {
	*mock.Call
}

// InsertMetricSample is a helper method to define mock.On call
//   - seriesID int64
//   - value float64
//   - timestamp *int64
func (_e *MockInternalDB_Expecter) InsertMetricSample(seriesID interface{}, value interface{}, timestamp interface{}) *MockInternalDB_InsertMetricSample_Call {
	return &MockInternalDB_InsertMetricSample_Call{Call: _e.mock.On("InsertMetricSample", seriesID, value, timestamp)}
}

func (_c *MockInternalDB_InsertMetricSample_Call) Run(run func(seriesID int64, value float64, timestamp *int64)) *MockInternalDB_InsertMetricSample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInternalDB_InsertMetricSample_Call) Return(err error) *MockInternalDB_InsertMetricSample_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_InsertMetricSample_Call) RunAndReturn(run func(seriesID int64, value float64, timestamp *int64) error) *MockInternalDB_InsertMetricSample_Call {
	_c.Call.Return(run)
	return _c
}

// MigrateDown provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) MigrateDown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MigrateDown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_MigrateDown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrateDown'
type MockInternalDB_MigrateDown_Call struct {
	*mock.Call
}

// MigrateDown is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) MigrateDown() *MockInternalDB_MigrateDown_Call {
	return &MockInternalDB_MigrateDown_Call{Call: _e.mock.On("MigrateDown")}
}

func (_c *MockInternalDB_MigrateDown_Call) Run(run func()) *MockInternalDB_MigrateDown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_MigrateDown_Call) Return(err error) *MockInternalDB_MigrateDown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_MigrateDown_Call) RunAndReturn(run func() error) *MockInternalDB_MigrateDown_Call {
	_c.Call.Return(run)
	return _c
}

// MigrateUp provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) MigrateUp() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MigrateUp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_MigrateUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrateUp'
type MockInternalDB_MigrateUp_Call struct {
	*mock.Call
}

// MigrateUp is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) MigrateUp() *MockInternalDB_MigrateUp_Call {
	return &MockInternalDB_MigrateUp_Call{Call: _e.mock.On("MigrateUp")}
}

func (_c *MockInternalDB_MigrateUp_Call) Run(run func()) *MockInternalDB_MigrateUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_MigrateUp_Call) Return(err error) *MockInternalDB_MigrateUp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_MigrateUp_Call) RunAndReturn(run func() error) *MockInternalDB_MigrateUp_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultSettings provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) SetDefaultSettings() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_SetDefaultSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultSettings'
type MockInternalDB_SetDefaultSettings_Call struct {
	*mock.Call
}

// SetDefaultSettings is a helper method to define mock.On call
func (_e *MockInternalDB_Expecter) SetDefaultSettings() *MockInternalDB_SetDefaultSettings_Call {
	return &MockInternalDB_SetDefaultSettings_Call{Call: _e.mock.On("SetDefaultSettings")}
}

func (_c *MockInternalDB_SetDefaultSettings_Call) Run(run func()) *MockInternalDB_SetDefaultSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInternalDB_SetDefaultSettings_Call) Return(err error) *MockInternalDB_SetDefaultSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_SetDefaultSettings_Call) RunAndReturn(run func() error) *MockInternalDB_SetDefaultSettings_Call {
	_c.Call.Return(run)
	return _c
}

// SetSetting provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) SetSetting(key string, value string, userID *int64) error {
	ret := _mock.Called(key, value, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *int64) error); ok {
		r0 = returnFunc(key, value, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_SetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSetting'
type MockInternalDB_SetSetting_Call struct {
	*mock.Call
}

// SetSetting is a helper method to define mock.On call
//   - key string
//   - value string
//   - userID *int64
func (_e *MockInternalDB_Expecter) SetSetting(key interface{}, value interface{}, userID interface{}) *MockInternalDB_SetSetting_Call {
	return &MockInternalDB_SetSetting_Call{Call: _e.mock.On("SetSetting", key, value, userID)}
}

func (_c *MockInternalDB_SetSetting_Call) Run(run func(key string, value string, userID *int64)) *MockInternalDB_SetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInternalDB_SetSetting_Call) Return(err error) *MockInternalDB_SetSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_SetSetting_Call) RunAndReturn(run func(key string, value string, userID *int64) error) *MockInternalDB_SetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// SetSettingIfNotExists provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) SetSettingIfNotExists(key string, value string, userID *int64) error {
	ret := _mock.Called(key, value, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetSettingIfNotExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *int64) error); ok {
		r0 = returnFunc(key, value, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_SetSettingIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSettingIfNotExists'
type MockInternalDB_SetSettingIfNotExists_Call struct {
	*mock.Call
}

// SetSettingIfNotExists is a helper method to define mock.On call
//   - key string
//   - value string
//   - userID *int64
func (_e *MockInternalDB_Expecter) SetSettingIfNotExists(key interface{}, value interface{}, userID interface{}) *MockInternalDB_SetSettingIfNotExists_Call {
	return &MockInternalDB_SetSettingIfNotExists_Call{Call: _e.mock.On("SetSettingIfNotExists", key, value, userID)}
}

func (_c *MockInternalDB_SetSettingIfNotExists_Call) Run(run func(key string, value string, userID *int64)) *MockInternalDB_SetSettingIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInternalDB_SetSettingIfNotExists_Call) Return(err error) *MockInternalDB_SetSettingIfNotExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_SetSettingIfNotExists_Call) RunAndReturn(run func(key string, value string, userID *int64) error) *MockInternalDB_SetSettingIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFileRevisionPath provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) UpdateFileRevisionPath(tx *goqu.TxDatabase, revisionID int64, revisionPath string, updatedBy int64) error {
	ret := _mock.Called(tx, revisionID, revisionPath, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFileRevisionPath")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*goqu.TxDatabase, int64, string, int64) error); ok {
		r0 = returnFunc(tx, revisionID, revisionPath, updatedBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_UpdateFileRevisionPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFileRevisionPath'
type MockInternalDB_UpdateFileRevisionPath_Call struct {
	*mock.Call
}

// UpdateFileRevisionPath is a helper method to define mock.On call
//   - tx *goqu.TxDatabase
//   - revisionID int64
//   - revisionPath string
//   - updatedBy int64
func (_e *MockInternalDB_Expecter) UpdateFileRevisionPath(tx interface{}, revisionID interface{}, revisionPath interface{}, updatedBy interface{}) *MockInternalDB_UpdateFileRevisionPath_Call {
	return &MockInternalDB_UpdateFileRevisionPath_Call{Call: _e.mock.On("UpdateFileRevisionPath", tx, revisionID, revisionPath, updatedBy)}
}

func (_c *MockInternalDB_UpdateFileRevisionPath_Call) Run(run func(tx *goqu.TxDatabase, revisionID int64, revisionPath string, updatedBy int64)) *MockInternalDB_UpdateFileRevisionPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *goqu.TxDatabase
		if args[0] != nil {
			arg0 = args[0].(*goqu.TxDatabase)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInternalDB_UpdateFileRevisionPath_Call) Return(err error) *MockInternalDB_UpdateFileRevisionPath_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_UpdateFileRevisionPath_Call) RunAndReturn(run func(tx *goqu.TxDatabase, revisionID int64, revisionPath string, updatedBy int64) error) *MockInternalDB_UpdateFileRevisionPath_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFileRevisionStatus provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) UpdateFileRevisionStatus(tx *goqu.TxDatabase, revisionID int64, status string, updatedBy int64) error {
	ret := _mock.Called(tx, revisionID, status, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFileRevisionStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*goqu.TxDatabase, int64, string, int64) error); ok {
		r0 = returnFunc(tx, revisionID, status, updatedBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_UpdateFileRevisionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFileRevisionStatus'
type MockInternalDB_UpdateFileRevisionStatus_Call struct {
	*mock.Call
}

// UpdateFileRevisionStatus is a helper method to define mock.On call
//   - tx *goqu.TxDatabase
//   - revisionID int64
//   - status string
//   - updatedBy int64
func (_e *MockInternalDB_Expecter) UpdateFileRevisionStatus(tx interface{}, revisionID interface{}, status interface{}, updatedBy interface{}) *MockInternalDB_UpdateFileRevisionStatus_Call {
	return &MockInternalDB_UpdateFileRevisionStatus_Call{Call: _e.mock.On("UpdateFileRevisionStatus", tx, revisionID, status, updatedBy)}
}

func (_c *MockInternalDB_UpdateFileRevisionStatus_Call) Run(run func(tx *goqu.TxDatabase, revisionID int64, status string, updatedBy int64)) *MockInternalDB_UpdateFileRevisionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *goqu.TxDatabase
		if args[0] != nil {
			arg0 = args[0].(*goqu.TxDatabase)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInternalDB_UpdateFileRevisionStatus_Call) Return(err error) *MockInternalDB_UpdateFileRevisionStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_UpdateFileRevisionStatus_Call) RunAndReturn(run func(tx *goqu.TxDatabase, revisionID int64, status string, updatedBy int64) error) *MockInternalDB_UpdateFileRevisionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionLastAccessed provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) UpdateSessionLastAccessed(sessionID string) error {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionLastAccessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_UpdateSessionLastAccessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionLastAccessed'
type MockInternalDB_UpdateSessionLastAccessed_Call struct {
	*mock.Call
}

// UpdateSessionLastAccessed is a helper method to define mock.On call
//   - sessionID string
func (_e *MockInternalDB_Expecter) UpdateSessionLastAccessed(sessionID interface{}) *MockInternalDB_UpdateSessionLastAccessed_Call {
	return &MockInternalDB_UpdateSessionLastAccessed_Call{Call: _e.mock.On("UpdateSessionLastAccessed", sessionID)}
}

func (_c *MockInternalDB_UpdateSessionLastAccessed_Call) Run(run func(sessionID string)) *MockInternalDB_UpdateSessionLastAccessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalDB_UpdateSessionLastAccessed_Call) Return(err error) *MockInternalDB_UpdateSessionLastAccessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_UpdateSessionLastAccessed_Call) RunAndReturn(run func(sessionID string) error) *MockInternalDB_UpdateSessionLastAccessed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPassword provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) UpdateUserPassword(userID int64, newPassword string, updatedBy int64) error {
	ret := _mock.Called(userID, newPassword, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, string, int64) error); ok {
		r0 = returnFunc(userID, newPassword, updatedBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_UpdateUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPassword'
type MockInternalDB_UpdateUserPassword_Call struct {
	*mock.Call
}

// UpdateUserPassword is a helper method to define mock.On call
//   - userID int64
//   - newPassword string
//   - updatedBy int64
func (_e *MockInternalDB_Expecter) UpdateUserPassword(userID interface{}, newPassword interface{}, updatedBy interface{}) *MockInternalDB_UpdateUserPassword_Call {
	return &MockInternalDB_UpdateUserPassword_Call{Call: _e.mock.On("UpdateUserPassword", userID, newPassword, updatedBy)}
}

func (_c *MockInternalDB_UpdateUserPassword_Call) Run(run func(userID int64, newPassword string, updatedBy int64)) *MockInternalDB_UpdateUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInternalDB_UpdateUserPassword_Call) Return(err error) *MockInternalDB_UpdateUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_UpdateUserPassword_Call) RunAndReturn(run func(userID int64, newPassword string, updatedBy int64) error) *MockInternalDB_UpdateUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserRoles provides a mock function for the type MockInternalDB
func (_mock *MockInternalDB) UpdateUserRoles(userID int64, roles string, updatedBy int64) error {
	ret := _mock.Called(userID, roles, updatedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserRoles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, string, int64) error); ok {
		r0 = returnFunc(userID, roles, updatedBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalDB_UpdateUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserRoles'
type MockInternalDB_UpdateUserRoles_Call struct {
	*mock.Call
}

// UpdateUserRoles is a helper method to define mock.On call
//   - userID int64
//   - roles string
//   - updatedBy int64
func (_e *MockInternalDB_Expecter) UpdateUserRoles(userID interface{}, roles interface{}, updatedBy interface{}) *MockInternalDB_UpdateUserRoles_Call {
	return &MockInternalDB_UpdateUserRoles_Call{Call: _e.mock.On("UpdateUserRoles", userID, roles, updatedBy)}
}

func (_c *MockInternalDB_UpdateUserRoles_Call) Run(run func(userID int64, roles string, updatedBy int64)) *MockInternalDB_UpdateUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInternalDB_UpdateUserRoles_Call) Return(err error) *MockInternalDB_UpdateUserRoles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalDB_UpdateUserRoles_Call) RunAndReturn(run func(userID int64, roles string, updatedBy int64) error) *MockInternalDB_UpdateUserRoles_Call {
	_c.Call.Return(run)
	return _c
}
